### ISSUE TITLE
Feature: order of additionalPrinterColumns

### ISSUE THREAD

**Issue by stefanbethke** [java-operator-sdk/java-operator-sdk#1028]
Unless I've missed it, it is not possible to influence the order of `@PrinterColumn`s in the CRD. It seems to be ordered alphabetically. 

I have two printer columns `.status.milestone` and `.status.error`, and I would like them printed in that order. However, right now error comes first.

I can work around this by manually swapping the entries in the CRD, and it's only cosmetic anyway, but it would be nice to have.

**Comment by scrocquesel** [comment]
Hi,

CRD generation is done by https://github.com/fabric8io/kubernetes-client. `PrinterColumn` ordering was made consistent by https://github.com/fabric8io/kubernetes-client/issues/3153. If you need fine-grained control, you should open an issue there.

**Comment by stefanbethke** [comment]
Opened an issue over on the client.

**Comment by metacosm** [comment]
Thank you!
