### ISSUE TITLE
MySQLSchema Sample E2E test issues

### ISSUE THREAD

**Issue by csviri** [java-operator-sdk/java-operator-sdk#1047]
MYSQLSchema sample has some strange behavior, especially when it takes to cleanup - does not seems to be working. The goal of this issue is to improve this test, to cover delete and improve the handling of port forwarding and related logging.

**Comment by scrocquesel** [comment]
Do you have any logs to look at ? Is it with local or remote testing ?

**Comment by csviri** [comment]
It's with both, try for example to delete the resources from the test at the end and wait for the cleanup. That part should fail.

**Comment by scrocquesel** [comment]
I don't reproduce it locally, I push a draft refactoring around port forwarding and a delete resource to mysql. Let me know if this is what you were thinking about.
