### ISSUE TITLE
Opinionated way to build Docker image

### ISSUE THREAD

**Issue by adam-sandor** [java-operator-sdk/java-operator-sdk#105]
The SDK should help with building a Docker image. If we would use Quarkus (#65) , that would solve this problem, but would not be compatible with Spring Boot. I think we should have both a Quarkus and Spring Boot distribution of the SDK both doing Docker builds in their own "native" way.

**Comment by jmrodri** [comment]
@adam-sandor native as in native to quarkus and native to spring boot? or did you mean native as in native Docker?

**Comment by jmrodri** [comment]
The [Operator Framework Operator SDK](https://github.com/operator-framework/operator-sdk/) (o-f/operator-sdk) scaffolds out Dockerfiles  . Here's the ansible project dockerfile template: https://github.com/operator-framework/operator-sdk/blob/master/internal/plugins/ansible/v1/scaffolds/internal/templates/dockerfile.go

We and kubebuilder took the Dockerfile approach. The idea being that you build your operator (for Go) or simply copy the playbook yaml files (for Ansible) into the container. All the commands are simply listed in the Dockefile of your generated project which you can amend as you see fit.  Having a Dockerfile at the root of the project is very common for operator projects and other kubernetes native applications.

**Comment by jmrodri** [comment]
The one thing I don't like about the current jib that we are using in the java-operator-plugins scaffolder is that it creates the image but you don't see how. So it's weird to figure out how to modify what will go into the image. Maybe we don't want that.

**Comment by adam-sandor** [comment]
I meant native to Quarkus and Spring Boot. Quarkus has an extension that essentially wraps Jib, I'm not sure if SB has a "native" way to build images. You can configure what goes into the image using Jib's configuration, but obviously a Dockerfile is better understood by more people.

I'm not against using a Dockerfile at all, but there will be some tough choices to be made in that case:
1. We could build an uber-jar with Maven and just COPY it in into the image. In this case the build isn't fully Docker-reproducible.
2. Use a multi-stage Docker build that creates an uber-jar and copies it into the next stage with dependencies pulled on every build.
3. Same as 2, but do the dependency pull in a separate layer so it only happens when the deps change. Unfortunately this requires a hack to do with Maven (https://gist.github.com/adam-sandor/9c87cc743392bfe5e778c4486a097154). When we are talking about "The Way" to build Docker image with the SDK even such a small hack can lead to lot of headache.

Also the building of the uber-jar is different depending on whether you do it with Quarkus, Spring Boot, or vanilla Java. 

So yeah.. not easy answers here I'd say. We'll have to pick what criteria are most important for us (least amount of config, compatibility with non-java sdk-s, etc) and build the solution around that.

**Comment by csviri** [comment]
Will close this issue, since it is not on the radar for a long time, we can reopen in case it pops up in discussions again.
