### ISSUE TITLE
Generate CRD from Custom Resource POJO

### ISSUE THREAD

**Issue by csviri** [java-operator-sdk/java-operator-sdk#110]
https://www.eclipse.org/jkube/ might have some stuff we can reuse for this

**Comment by psycho-ir** [comment]
I can think of 2 ways to implement this feature. 
1. A CLI application
2. A plugin for the popular build tools like Maven & Gradle.

What I like about Option 1 is that it's build tools agnostic and we still have this possibility to build the plugins for build tools on top of it.

Would be great if you could share your thoughts about this feature anytime you have time.
@adam-sandor @csviri @kirek007  @metacosm

**Comment by csviri** [comment]
@psycho-ir I think those are not mutually exclusive, I would implement it as a library (a maven module), than wrap it into a CLI and/or Maven plugin.

**Comment by metacosm** [comment]
We already have something that deals with this in our dekorate.io project, though it might be interesting to see if we could avoid importing the whole project to benefit from that feature. We're also discussing whether the custom resource support that's currently in Dekorate wouldn't make more sense to be included in the Fabric8 client directly.

**Comment by psycho-ir** [comment]
After checking the dekorate, figured out I commented on the wrong issue 🤦 .
I think generating the POJOs from the CRDs would be more useful, the ones who want to write an operator already know how to write a manifest and there are plenty of documents to help them. 
I move my previous comment to #28 to discuss that topic further.

**Comment by lordofthejars** [comment]
Hello, if you want I can develop 2 Java classes (one for JSON using JSON-P dep and another for YAML using snakeYAML) taht reads a CRD and generate the Java files. I know this is not a plugin nor a CLI tool, but then you'll be able to use these classes there.

**Comment by metacosm** [comment]
This is now fixed by using the `crd-generator` functionality provided by fabric8's kubernetes-client project as shown in #350.
