### ISSUE TITLE
Feature flag for `fail fast` behavior for Managed Dependent Resources

### ISSUE THREAD

**Issue by csviri** [java-operator-sdk/java-operator-sdk#1107]
Currently the behavior in managed dependent resource is the following:
We reconcile all the dependent resources mentioned in the `@Dependent` annotation in order. So calling `reconcile(...)` on all dependents, even if one of the fails. If one fails eventually we will throw the exception, but before all others are reconciled.

This is reasonable if the resources are independent of each other. If there is a problem with one that will be retried again (as the result of the exception , that triggers eventually a new reconciliation). 

However this behavior is not so nice, if those dependent are interconnected, thus depend on each other. If one fails, and an other depends on it, the "other" will fail too. In this case a desired behavior would be not to reconcile the other. 

One way to handle this in general is to give an option to the users, to have a **fail fast** approach. To have a feature flag to configure the controller to have fail after the first exception occurred. This is more consistent also with the implementation of the reconciler where users don't use dependent resources or use them in standalone mode. The exception is thrown and can be handled by `ErrorStatusHandler`.

**Comment by csviri** [comment]
Note that this issue is also related to workflows: https://github.com/java-operator-sdk/java-operator-sdk/issues/1097 we might eventually implement.

**Comment by metacosm** [comment]
In my opinion, it'd be better to focus on implementing simple workflow support than adding a feature flag because this flag will be obsolete with the workflow support.

**Comment by csviri** [comment]
I agree that should be the primary goal. But can take some time.  
Created this to be on the table if we see lots of issues with the current default approach.

**Comment by csviri** [comment]
Implemented workflows with the  "most complete" approach, this is what @metacosm is preferred (if remember correctly), will close this issue.
