### ISSUE TITLE
Access to the primary resource informer during prepare the event source

### ISSUE THREAD

**Issue by Aitozi** [java-operator-sdk/java-operator-sdk#1114]
Hi community, when I use the SDK to build operator for this scene:

A primary resource called resourceA and secondary resourceB. 

When I try to register the event source for resourceB, resourceB can not directly reflect to the primary resourceA by metadata. It have to access the resourceA by filtering the list resource cache, I think it's inefficient. So I want to build an indexer for resourceA from the internal controllerEventSource. 

But the controllerEventSource is start after the prepareEventSource finished. So we can't access to the primary resource informer. Do you guys think this can be supported ?

Thanks

**Comment by metacosm** [comment]
Which version of the SDK are you using? Could detail your use case more concretely, please?

**Comment by csviri** [comment]
@Aitozi you are not able to use a naming convention to access that resource? Based on what properties you access it now?

**Comment by Aitozi** [comment]
Thanks for your response. I am using `<operator.sdk.version>2.1.2</operator.sdk.version>`. I will try to make the case more clear. Let's assume there are two types called `CLUSTER` and `JOB`. These two CR are managed by an operator. The reconciler for the `job` need to wait for `cluster` ready before submitting `job` to the `cluster`. So I want to also react to the event source from the `cluster`. 
But the `cluster`  can not be directly mapping to which `job` to notify, It needs to filter the `job.spec.cluster=cluster.name` to find the target `jobs`. 
So I want to build an index for the `job.spec.cluster` when I prepareEventSource for the `job` reconciler, By this, I can directly get the target `job` when a `cluster` resource changed.

**Comment by Aitozi** [comment]
Because the controllerEventSource are start after the prepareEventSource, So when prepareEventSource, I can't build an Indexer for the `job` type.

**Comment by csviri** [comment]
Ok, so what you would like to do (ideally), is in the prepareEventSources, you would build an index based on the cache of the `ControllerEventSource` (let's assume it's started and synced that moment) ?

**Comment by csviri** [comment]
A solution that might feel little hackish is:
In the reconcile method of `Job`, I would update the index (empty at the start), so not in the `prepareEventSource`. If the job is reconciled you can read the cluster, update a map that will contain <cluster, job resource id list> , will put the job resource ID in the proper cluster name. And in the event source mapper, you would just simply use this map, and return that list to be reconciled if changed.

**Comment by csviri** [comment]
> Because the controllerEventSource are start after the prepareEventSource, So when prepareEventSource, I can't build an Indexer for the `job` type.
By indexer you mean really the Informer Indexer or a custom one?

**Comment by Aitozi** [comment]
> > Because the controllerEventSource are start after the prepareEventSource, So when prepareEventSource, I can't build an Indexer for the `job` type.
> 
> By indexer you mean really the Informer Indexer or a custom one?

the informer indexer for `<cluster to job>` relation, to support find a cluster's job.

**Comment by Aitozi** [comment]
> 

I'm not meant to maintain the indexer myself, just create a informer indexer

**Comment by Aitozi** [comment]
> A solution that might feel little hackish but might work:
> 
> In the `reconcile(..)` method for `Job`, I would update the index (empty at the start), so not in the `prepareEventSource`. If the job is reconciled you can read the cluster, update a map that will contain <cluster, job resource id list> , will put the job resource ID in the proper cluster name. And in the event source mapper, you would just simply use this map, and return that list to be reconciled if changed.
> 
> Also remove the resource id from that map on cleanup.
> 
> But you can also add event handler to the Informer, that might be more elegant solution. Just as far I can see there is no API for that, now to access the `ControllerEventSource`.

I'm not meant to maintain the indexer myself,  Just create an informer indexer

**Comment by metacosm** [comment]
Couldn't the primary to secondary mappers be used in that case so that the cluster events would trigger the appropriate job reconciliation?

**Comment by csviri** [comment]
> But the controllerEventSource is start after the prepareEventSource finished. So we can't access to the primary resource informer. Do you guys think this can be supported ?

I think yes, not sure if we should start first the event source, probably not. I guess handling an additional indexer should be there. This is a totally valid feature / use case. 

( We plan to release 3.0 soon, but I guess I can take a look on this right after if that good enough. Until that time maybe just stick with un-efficient way or a custom dummy indexind as mentioned above  )

**Comment by Aitozi** [comment]
> Couldn't the primary to secondary mappers be used in that case so that the cluster events would trigger the appropriate job reconciliation?

primary to secondary mappers seems only work when we can directly decide the primary resource by the secondary metadatas. If we have to list the primary resource and filter it will be inefficient I think

**Comment by Aitozi** [comment]
> > But the controllerEventSource is start after the prepareEventSource finished. So we can't access to the primary resource informer. Do you guys think this can be supported ?
> 
> I think yes, not sure if we should start first the event source, probably not. Handling an additional indexer should be there. This is a totally valid feature / use case.
> 
> ( We plan to release 3.0 soon, but I guess I can take a look on this right after if that good enough. Until that time maybe just stick with un-efficient way or a custom dummy indexind as mentioned above )

I'm trying to work around by register an additional informer with indexer, Looking forward to your progress on this, thanks

**Comment by csviri** [comment]
Problem is that we cannot just create/start the informers before, would have effect on whole logic. 
In v3.0 we anyways have a nicer (unfortunatelly also more complex) abstractions over informers. 
Probably will create an explicit api for additional indexers. To make this very clean.

**Comment by Aitozi** [comment]
Besides the way to get the controller informer is not very clear not, It has to be casted 

```
ControllerResourceEventSource<FlinkSessionJob> resourceEventSource =
                (ControllerResourceEventSource<FlinkSessionJob>)
                        eventSourceContext.getPrimaryCache();
resourceEventSource.getInformer()
```

**Comment by csviri** [comment]
yes, that should be accessable there. Will add that too within this issue.

**Comment by csviri** [comment]
Just for the record, fabric8 client is going to change the informers and the caching in informers significantly in upcoming major version, the plan is that the caching will be handled by us eventually, so the indexing is also probably. So will try to design an interface that ideally will hide these implementation details in the background.

**Comment by csviri** [comment]
> > > But the controllerEventSource is start after the prepareEventSource finished. So we can't access to the primary resource informer. Do you guys think this can be supported ?
> > 
> > 
> > I think yes, not sure if we should start first the event source, probably not. Handling an additional indexer should be there. This is a totally valid feature / use case.
> > ( We plan to release 3.0 soon, but I guess I can take a look on this right after if that good enough. Until that time maybe just stick with un-efficient way or a custom dummy indexind as mentioned above )
> 
> I'm trying to work around by register an additional informer with indexer, Looking forward to your progress on this, thanks

Pls let us know how it went.

**Comment by Aitozi** [comment]
@csviri It works as expected. If not bother, you can refer to [here](https://github.com/Aitozi/flink-kubernetes-operator/blob/d784f52cd257892db622347bb1446dd78effb78c/flink-kubernetes-operator/src/main/java/org/apache/flink/kubernetes/operator/controller/FlinkSessionJobController.java#L181) for a look
