### ISSUE TITLE
The operator should stay in CrashLoopBackoff if the CRD is not installed

### ISSUE THREAD

**Issue by andreaTP** [java-operator-sdk/java-operator-sdk#1136]
## Bug Report

Starting an operator without having the CRDs installed should result in an Exception in initialization that would restart the pod.

#### What did you do?

You can reproduce the behaviour with the Keycloak nightly on minikube:

```
kubectl apply -f https://raw.githubusercontent.com/keycloak/keycloak-k8s-resources/nightly/kubernetes/minikube.yml
```

#### What did you expect to see?

The operator pod goes in CrashLoopBackoff

#### What did you see instead? Under which circumstances?

The operator pod goes into the Running state, but the Informers are not going to notify any event for the managed CRDs.

This is especially problematic when applying resources all together in a cluster (e.g. CRDs operators etc. etc.) since the following can happen:
 - the operator gets created
 - the CRDs are created
 - the user creates a CR
 - nothing happens since the operator is in "Running" state but the Informers are not in place

#### Environment

minikube

`Quarkus Operator SDK 3.0.6`

#### Possible Solution

Exceptions thrown by the informers should crash the Operator.

cc.: @vmuzikar

**Comment by metacosm** [comment]
Closed in favour of https://github.com/quarkiverse/quarkus-operator-sdk/issues/295 as this is a Quarkus extension issue, I think.

**Comment by metacosm** [comment]
This is actually indeed an issue with the SDK, not the extension. 😓

**Comment by andreaTP** [comment]
@metacosm @csviri let me know if you need any help on this, we are going to release a preview those days and, if we can't get it fixed in the SDK, I'll have to go ahead and implement a workaround in the operator at least.

For @csviri , this fix might (or might not...) impact the analysis we did regarding multiple CRDs versions, when we have been "relying" on Informers failing in background.

**Comment by metacosm** [comment]
@andreaTP would be great if you could give the associated PR a try and let us know how it works out for you…

**Comment by csviri** [comment]
@andreaTP @metacosm I guess this should be true for both the Operator's main CR and the InformerEventSources registered.

**Comment by andreaTP** [comment]
@csviri would you mind to elaborate on:

> @andreaTP @metacosm I guess this should be true for both the Operator's main CR and the InformerEventSources registered.

e.g. if you register an `EventSource` on Labelled Secrets is totally fine to go into the running state even if there is no Labelled Secret in the cluster yet.

**Comment by csviri** [comment]
@andreaTP I meant that this issue is totally valid both for main CR and possible CRs related to Informers. Sorry if was not clear.

**Comment by andreaTP** [comment]
Thanks 👍
