### ISSUE TITLE
Support building control loops for eventless resources

### ISSUE THREAD

**Issue by adam-sandor** [java-operator-sdk/java-operator-sdk#114]
If a controller creates resources that don't provide lifecycle events (e.g. MySQL schema) there is no nice way to implement the full control loop. I'm thinking we should add a new (optional) `monitor` method to the controller which would get the list of all resources and could do a check if the target resources are in the right state. The framework could call this method periodically.

**Comment by jmrodri** [comment]
@adam-sandor can you elaborate more? @metacosm mentioned during our triage meeting that this might be covered by some other mechanism.

**Comment by csviri** [comment]
@adam-sandor I think this is covered by event sources, so you can watch for changes there, possibly periodically checking the target system. Then omit an event execute the controller and reconcile the target state there.

**Comment by adam-sandor** [comment]
Yes this is covered by event sources now. We can close it.

**Comment by metacosm** [comment]
Thank you!
