### ISSUE TITLE
Support status update also with optimistic locking

### ISSUE THREAD

**Issue by csviri** [java-operator-sdk/java-operator-sdk#1156]
When we removed the deprecated API for status update and started to use the new api:
https://github.com/java-operator-sdk/java-operator-sdk/blob/553e389edb257f70f4c8eeeda4d4755ad4786b58/operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/event/ReconciliationDispatcher.java#L355-L355

Found that there is a little different behavior, before it failed on optimistic locking but this version is not. It's better to have optimistic locking there because of cache consistency, see details here:

https://github.com/fabric8io/kubernetes-client/pull/3943#issuecomment-1097171960

Update:
- the preferred way is to do status updated without optimistic locking (patch)
- however we still might want to have this in the future when possible.

**Comment by scrocquesel** [comment]
+1, when updating status, it should be in sync with the spec revision fetched from the cache, because some operators are actually copying spec data to status.

**Comment by csviri** [comment]
Will do this at most we migrate to the new fabric8 client (v6). Before it would be quite hacky but will check how it would look like.

**Comment by csviri** [comment]
>  because some operators are actually copying spec data to status.

It this actually a problem without optimistic locking? in the reconciliation when spec is copied, it copies the actual not the latest (if changed meanwhile) , what seems to be correct for me. So if spec changes, it will anyways reconcile again with new specs.

**Comment by metacosm** [comment]
I don't think that status should be updated using optimistic locking. The status should be separated from the spec anyway so it should be possible to update it independently of the spec and without triggering a new reconciliation. In fact, it should technically be possible to update different part of the status independently as well and possibly from different actors (e.g. a different controller) without causing a conflict on the resource because the status should not be part of the version of the resource, imo.

**Comment by csviri** [comment]
It is possible already to update some parts using `patch`. 
(Technically in `etcd` is part of the resource.)
It is not triggering reconciliation by default now because of the generation filtering, but it also possible to make it not trigger reconciliaiton without generation filtering, probably that would be the best (Although might be opinionated)

**Comment by scrocquesel** [comment]
> > because some operators are actually copying spec data to status.
> 
> It this actually a problem without optimistic locking? in the reconciliation when spec is copied, it copies the actual not the latest (if changed meanwhile) , what seems to be correct for me. So if spec changes, it will anyways reconcile again with new specs and override also specs in status.

If you can guarantee that a reconciliation will be triggered, right after status update (at least if generation changed). Yes. It should not make any difference.

But I think that it will not. To me, 
Reconcile is triggered on revision 1, generation 1, spec and generation is to be set to status, but meanwhile, something change the spec to revision 2, generation 2. I guess, the event is discard because a reconciliation is already ongoing.
Status, is updated forcibly with spec rev1 and gen1 and produce revision 3.
No more event, no more triggering until the operator is restarted (or if a max reconcile time period is set).

**Comment by csviri** [comment]
> If you can guarantee that a reconciliation will be triggered, right after status update (at least if generation changed). Yes. It should not make any difference.

if you set `generationAwareEventProcessing` to `false`, it will trigger.

`The event for rev2/gen2 is discarded because a reconciliation is still ongoing.`  - this is not true, it will trigger the reconciliation. Since there is a new generation.

**Comment by scrocquesel** [comment]
> > If you can guarantee that a reconciliation will be triggered, right after status update (at least if generation changed). Yes. It should not make any difference.
> 
> if you set `generationAwareEventProcessing` to `false`, it will triggered even on status updates.
> 

IMHO, setting it to false should be for edge cases.

> > `The event for rev2/gen2 is discarded because a reconciliation is still ongoing.`
> 
> this is not true, it will trigger the reconciliation, since there is a new generation. Even is there were other updates after - it does not matter - the custom resource is already marked to be reconciled again. So it will be reconciled when the previous reconciliation finished.

I didn't know that. If so, then, yes. No locking mechanism could help.

> In fact, it should technically be possible to update different part of the status independently as well and possibly from different actors (e.g. a different controller) without causing a conflict on the resource because the status should not be part of the version of the resource, imo.

Then, if we force the patch of status without locking mechanism, we need to assume that there can be lost update in the wild. Especially, patching the same fields could lead to unwanted result. For eg. patching an array of conditions may loose some conditions.

I guess optimistic should be the default as it is the safest (and the historic behavior) and one can disable it.

**Comment by metacosm** [comment]
> > In fact, it should technically be possible to update different part of the status independently as well and possibly from different actors (e.g. a different controller) without causing a conflict on the resource because the status should not be part of the version of the resource, imo.
> 
> Then, if we force the patch of status without locking mechanism, we need to assume that there can be lost update in the wild. Especially, patching the same fields could lead to unwanted result. For eg. patching an array of conditions may loose some conditions.
> 

Understood. However, there are no guarantees made by the cluster that the status will be correct at any given point in time, it's more a best effort kind of deal where the cluster will attempt to provide an accurate account of its current state but it shouldn't be relied upon and should always be re-buildable from the observed state during reconciliation. 

More specifically, status shouldn't be used to store "application" state that would be needed by controllers to perform their logic correctly.

**Comment by csviri** [comment]
Merged the related PR. Now we support both approaches.
