### ISSUE TITLE
`DependentResource` support for event sources where multiple resources of same type are handled for single primary

### ISSUE THREAD

**Issue by csviri** [java-operator-sdk/java-operator-sdk#1175]
In the following PR: https://github.com/java-operator-sdk/java-operator-sdk/pull/1169 we made sure that every resource event source can handle multiple secondary resources for a primary. A dependent resource however now represents a single resource on cluster. So in order to share a event source between more resource that are (the same type and) related to a single primary resources, we would need to **have a discriminator function**. So if a dependent resource receives from `Set<R> getSecondaryResources()` multiple resources this discriminator will select which one to handle from the set. 

This is a relative simple but useful way to support this case.

**Comment by grossws** [comment]
FtR: As a workaround for 3.2.x one could try to use distinct labels for different managed resources of the same type plus explicit `@Dependent(name = "some-name", type = SomeResource.class)` and then use either `context.getSecondaryResources(Deployment.class)` or `context.getSecondaryResource(Deployment.class, "some-name")` (but it could be deprecated in #1240). 

Not sure if it will lead for other issues though, so it's just a possible approach. I hope @csviri would correct me if it's a wrong way to do it in 3.2.x and if there's better approach.

As example of such approach there's my [reproducer project](https://github.com/grossws/operatorsdk-es-issue) for another issue.

**Comment by csviri** [comment]
Hi @grossws, in v4.1  (will are getting it released shortly) there will be an explicit support for that. But there is no other approach now in 3.2.
