### ISSUE TITLE
Release process for RCs shouldn't update the version to next patch release

### ISSUE THREAD

**Issue by metacosm** [java-operator-sdk/java-operator-sdk#1201]
Seems like currently the release process goes from 3.0.0.RCx-SNAPSHOT to 3.0.1-SNAPSHOT. It should move the version to 3.0.0-SNAPSHOT or 3.0.0.RC(x +1)-SNAPSHOT. Since 3.0.0 is not released, it doesn't make sense to move to 3.0.1-SNAPSHOT.

**Comment by csviri** [comment]
I think this is not true, in case of RC release the version is not updated.

**Comment by metacosm** [comment]
Well, something updated the version to `3.0.1-SNAPSHOT`, which is where `main` is currently at, which is wrong, imo. Not sure what updated the version but it definitely shouldn't be at `3.0.1-SNAPSHOT`. 😄

**Comment by csviri** [comment]
yeah, we should revert that manually, but afaik that happened between RC2 and RC3
