### ISSUE TITLE
Automated testing for samples

### ISSUE THREAD

**Issue by adam-sandor** [java-operator-sdk/java-operator-sdk#121]
To improve maintainability of our samples we should have good integration tests for them. This would include:
* compiling
* unit testing
* image building
* deploy to Kubernetes
* test business logic
So really comprehensive integration testing.

Once this is done we can add more samples like this one: https://github.com/ContainerSolutions/java-operator-sdk/pull/108

**Comment by csviri** [comment]
I think we have now this covered with E2E tests. Will close if no objections.
