### ISSUE TITLE
Reconciling clusterwide resource fails while adding the namespace to MDC

### ISSUE THREAD

**Issue by jasmdk** [java-operator-sdk/java-operator-sdk#1223]
#### What did you do?

Creating a reconciler watching a cluster wide resource (like "Namespace")

#### What did you expect to see?

I expected events to be issued like with Namespaced resources without exceptions in the log.

#### What did you see instead? Under which circumstances?

During activation of my reconciler, a nullpointer exception got thrown indicating that the metadata.namespace was added to MDC without validating that a namespace was present

#### Environment

**Kubernetes cluster type:**

"vanilla" - k3d

`$ Mention java-operator-sdk version from pom.xml file`

3.0.0.RC5

`$ java -version`

openjdk-11

`$ kubectl version`

Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.0", GitCommit:"ab69524f795c42094a6630298ff53f3c3ebab7f4", GitTreeState:"clean", BuildDate:"2021-12-07T18:16:20Z", GoVersion:"go1.17.3", Compiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.4+k3s1", GitCommit:"43b1cb48200d8f6af85c16ed944d68fcc96b6506", GitTreeState:"clean", BuildDate:"2022-02-24T22:38:17Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"linux/amd64"}

#### Possible Solution

https://github.com/java-operator-sdk/java-operator-sdk/blob/main/operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/MDCUtils.java#L32
Like with the generation field - only add it if it is present.

**Comment by csviri** [comment]
thank you @jasmdk , attached  a PR, pls review.
