### ISSUE TITLE
Support for multiple managed dependents of the same type

### ISSUE THREAD

**Issue by metacosm** [java-operator-sdk/java-operator-sdk#1273]
We need to make this use case work for managed dependent resources as well… I've started looking into it and will open as issue for it since we can't currently do it correctly. A potential way to fix the problem would be to use the `name` field of the `Dependent` annotation but I still need to hammer out the details.

_Originally posted by @metacosm in https://github.com/java-operator-sdk/java-operator-sdk/pull/1268#pullrequestreview-997721334_

**Comment by csviri** [comment]
Are you sure about this? Maybe we should start by writing an Integration tests, since I don't see why it should not work.

**Comment by csviri** [comment]
This is a duplicate: https://github.com/java-operator-sdk/java-operator-sdk/issues/1175

**Comment by csviri** [comment]
Closing this since its a duplicate.
