### ISSUE TITLE
Workflow Cycle Detection - Explicit Cycle Logging

### ISSUE THREAD

**Issue by csviri** [java-operator-sdk/java-operator-sdk#1277]
Workflows are essentially acyclic, detecting cycles is already implemented in PR: https://github.com/java-operator-sdk/java-operator-sdk/pull/1257

However this approach does not log the detected cycle - just logs that "there is a cycle" - thus nodes involved in the cycle. It would improve the developer experience if the cycle is clearly logged.

**Comment by csviri** [comment]
IMO this is a low priority issue since its not hard to find the cycles just by looking on the declaration of the workflow.

**Comment by metacosm** [comment]
Agreed, while my inner geek would like super neat graph algorithms and optimisations, we probably don't need them at this point.
