### ISSUE TITLE
Request to support OAuth Token as kubernetes client credentials in operator-framework-spring-boot-starter

### ISSUE THREAD

**Issue by zhannicholas** [java-operator-sdk/java-operator-sdk#1282]
In `operator-framework-spring-boot-starter` module, username/password authentication is supported for newly created kubernetes client. However, in some cases, username/password is unsupported and only OAuth token is supported, the later one is more secure. Maybe we can support both.

More details are in method `io.javaoperatorsdk.operator.springboot.starter.OperatorAutoConfiguration#getClientConfiguration`:
```java
xxx
.orElseGet(() -> {
          final var clientCfg = configuration.getClient();
          ConfigBuilder config = new ConfigBuilder();
          config.withTrustCerts(clientCfg.isTrustSelfSignedCertificates());
          clientCfg.getMasterUrl().ifPresent(config::withMasterUrl);
          clientCfg.getUsername().ifPresent(config::withUsername);
          clientCfg.getPassword().ifPresent(config::withPassword);
```

**Comment by zhannicholas** [comment]
> If you do nothing, the client should pick up the configuration from your `~/.kube/config` file where token authentication should work fine. Or do you need to explicitly configure which cluster to log to?

Sometimes, several kubeconfig files maybe exist. Another situations is about serviceAccount, we users (developers) may have a account with less permissions and an admin account (only available in k8s cluster) maybe more powerful, such as the rights to watch/update custom resources. If we leave all to `~/.kube/config`, this situation is a little bit difficult to handle with. But if we can log to a cluster explicitly, developer will suffer less.

**Comment by zhannicholas** [comment]
Another way is to let developer provide their own `kubernetesClient` Bean to override the defualt bean provided by the starter. But if the starter support this, it's more convenient.

**Comment by csviri** [comment]
Makes sense absolutely. Could we move this issue to the spring boot starter project @zhannicholas ? Would you mind to re-create it there?

**Comment by zhannicholas** [comment]
I open it in the wrong place, sorry for that, let me move it.

**Comment by zhannicholas** [comment]
Move it to the spring boot starter project. New issue is [operator-framework-spring-boot-starter issue 21](https://github.com/java-operator-sdk/operator-framework-spring-boot-starter/issues/21).
