### ISSUE TITLE
Documentation is confusing for Spring Boot

### ISSUE THREAD

**Issue by salaboy** [java-operator-sdk/java-operator-sdk#1312]
#### What did you do?

I am looking at this page: https://javaoperatorsdk.io/docs/using-samples 

Which shows a plain java, quarkus and spring boot examples. 

For Spring Boot it doesn't show how to start the operator, the current code in this repository shows how to do it but it took me quite a while to figure out where to look, as this should be explicit in the docs. 

https://github.com/java-operator-sdk/java-operator-sdk/blob/main/smoke-test-samples/spring-boot-plain/src/main/java/io/javaoperatorsdk/operator/sample/Config.java

There were also some references to classes that weren't mentioned on the using samples page. 

#### What did you expect to see?

How to get started with Spring Boot should be as complete as with plain and Quarkus. 

#### Environment

`java-operator-sdk` version 3.0.0 from maven central

#### Possible Solution

Updating the docs to be consistent for all the frameworks

**Comment by csviri** [comment]
Hi @salaboy , yes that page is not very well maintained, thx for pointing out and for the PR.
