### ISSUE TITLE
ReconcilerUtils.loadYaml should allow loading resources ready to build.

### ISSUE THREAD

**Issue by iocanel** [java-operator-sdk/java-operator-sdk#1334]
My understanding is that the the `ReconcilerUtils.loadYaml` is meant to load an initial yaml file and then programmatically modify it.
It would make sense for me to allow loading that resource directly as builder:

```java
DeploymentBuilder builder = ReconcilerUtils.loadYaml(DeploymentBuilder.class, getClass(), "deployment.yaml");
Deployment deployment = builder
    .accept(ContainerBuilder.class, c -> c.withImage("my-image")) 
    // More changes here
    .build();
```

**Comment by metacosm** [comment]
I've been thinking about implementing something like this for Quarkus… so that the YAML parsing / reflection could be done at build time. Not too sure how that would look like, though.
