### ISSUE TITLE
Improvements on `CachingInboundEventSource`

### ISSUE THREAD

**Issue by csviri** [java-operator-sdk/java-operator-sdk#1424]
Currently [`CachingInboundEventSource`](https://github.com/java-operator-sdk/java-operator-sdk/blob/95d25fe9ea6426f5a340f68544c199ac29a13575/operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/event/source/inbound/CachingInboundEventSource.java) has an issue with initialization of state. Currently the cache is only populated explicitly calling the `handleResourceEvent`. Therefore when related primary resources is reconciled the state might not be initialized. 

To fix this a resource fetching mechanism could be implemented, similarly as in `PerResourcePollingEventSource`, thus first time the primary resource appears it will initialize the state by fetching the target resource.

Optionally could have a cache expiration period, for the cases if some event is lost, making sure that if a longer period the resource is not refreshed, it is fetched it again.

**Comment by metacosm** [comment]
More generally speaking, I think our caches should be able to transparently check the API server if a resource is not found locally…

**Comment by csviri** [comment]
I'nm not sure how that would look like, also it really depends on type of resource and event source.  There are different behaviors, like `PerResourceEventSource` has completely different behavior than `PollingEventSource`. And I think it is good. So that the event sources populate the caches, with their specific behavior is the way to IMO.

**Comment by scrocquesel** [comment]
> More generally speaking, I think our caches should be able to transparently check the API server if a resource is not found locally…

Regarding external resource caching, at least, the cache should be able to handle staleness. Currently, the resource must be removed from the cache and it become complicated to detect if an event should be triggered especially on deleted resource.
