### ISSUE TITLE
Option to force-stop the reconciliation for a CR once it's deleted

### ISSUE THREAD

**Issue by LucaMertens** [java-operator-sdk/java-operator-sdk#1426]
When a resource is deleted while its `reconcile`-method is still running, reconciliation is finished before `cleanup` is executed.

This is a sensible default, but it would also be nice to let the SDK instantly stop reconciliation.
When deleting a resource that implements the `Cleaner`-Interface with Kubectl, it hangs until finalization is completed. Hence, the time until the CR-Lifecycle is finished can be visible to the user.

**Comment by csviri** [comment]
Hi @LucaMertens ,

why this would make sense, problem is there is no elegant way to do this, at least I'm not aware. We might interrupt the thread, to set the interrupted status, if you mean that.

**Comment by LucaMertens** [comment]
I just read up a bit on how to force-stop threads, and it seems to be slightly less straightforward than I thought 😅  As you stated, interrupting the thread is probably the only safe option. If the `reconcile` implementation is not cooperative, this accomplishes nothing, but it might still be a useful option.

**Comment by csviri** [comment]
Theoretically event if the custom resource changed or other event received the reconciliation might be stopped and executed again. However, by definition the reconciler implementation should be very fast to execute (although recognize that this is not always the case). 

Hmm, not sure if we should go this direction.

**Comment by csviri** [comment]
@metacosm what do you think?

**Comment by metacosm** [comment]
The only situations where such a feature would be worth the effort to implement it would be when the reconciliation process takes a long time or is really resource-intensive, in my opinion. Ideally, I agree that this feature would be nice to have but the applicability breadth and complexity of the implementation might not make it worth the effort, unfortunately, because it's kind of similar to implementing transactional integrity… 😅 

Do you have a use case @LucaMertens where implementing this would make a significant difference?

**Comment by csviri** [comment]
One case when this would not be desirable:
If controller manages an external resource, what is after creation referenced by an ID. These IDs are stored in ConfigMaps, so after creation if the resource a ConfigMap is created with the ID in it. If the reconciliation is interrupted between those steps, the external resource is created but not the configMap. So on cleanup it won't be deleted either.

**Comment by andreaTP** [comment]
I think that the current behavior is correct, and reconciliation should not be stopped before the finalizes are applied.
Every possible use case I can think about is overweighted by the fact that, stopping the reconcilation loop it's possible to end up in un-desirable states.

Do we have a compelling, real world example where not stopping the controller is going to harm?

**Comment by csviri** [comment]
> Do we have a compelling, real world example where not stopping the controller is going to harm?

Probably not, this mean to be a performance optimization. 

> Every possible use case I can think about is overweighted by the fact that, stopping the reconcilation loop it's possible to end up in un-desirable states.

yep, but to be honest I could just think about the one type of case mentioned above. Otherwise the reconcilers should be always idempotent.

**Comment by andreaTP** [comment]
> performance optimization

Any measurement to justify this?

Another case where stopping the reconciler is not desirable is when the operator detects cycles in the finalizers and can act upon those(e.g. deleting something), or at least, report  in the status the situation.

**Comment by csviri** [comment]
> Any measurement to justify this? 

It pretty much depends on the reconciler implementation. But IMO in generic case reoncilers are fast and can be implemented to be very fast, except when some resource (external usually) is created/updated - but there is no way around that, so makes sense to interrupt that only in case when a recent change would make that operation unnecessary. (talking not just about delete but also interrupt in case of any event)

So in general I'm rather against implementing this. We can also discuss on the weekly meeting.

**Comment by andreaTP** [comment]
I agree this is not desirable at this point in time unless a real, compelling use case pops up.

**Comment by LucaMertens** [comment]
> It's kind of similar to implementing transactional integrity… 😅

> One case when this would not be desirable: If controller manages an external resource, what is after creation referenced by an ID. These IDs are stored in ConfigMaps, so after creation if the resource a ConfigMap is created with the ID in it. If the reconciliation is interrupted between those steps, the external resource is created but not the configMap. So on cleanup it won't be deleted either.

> Another case where stopping the reconciler is not desirable is when the operator detects cycles in the finalizers and can act upon those(e.g. deleting something), or at least, report in the status the situation.

Okay, I didn't realize that this option introduces so many ways to shoot yourself in the foot. I agree that the effort far outweighs the benefits.

> Do you have a use case @LucaMertens where implementing this would make a significant difference?

We talked about how to implement a long-running task on Discord a few days ago. I'm essentially trying to implement a CR that behaves similar to K8s-Jobs, but has a custom spec and status and is limited to one concurrent execution.
Since there can only be one concurrent reconciliation for each custom resource, executing the task synchronously in the `reconcile`-method helps to ensure that there are no two parallel tasks across the cluster (for a given resource).
The task could then simply be cancelled by deleting the custom resource, which is where the interrupt of the Reconciler would come in handy.

However, similar behaviour can also be implemented on the user side by starting the task asynchronously from the reconciler and maintaining a map of type `CRName -> TaskThread` in the local state. I just thought that, since the JOSDK already implements the Thread-Safety logic by default (and probably better than I would write it), it would be smarter to use the framework for this task.

I know that this is quite a niche use case. In my mind, this feature was way simpler to implement, otherwise I wouldn't have suggested it. Thank you for your answers and I hope I didn't waste too much time with this issue!

**Comment by csviri** [comment]
Np, it's always good to discuss ideas like this. Thank you raising it! 

(Will close the issue for now)
