### ISSUE TITLE
Alter Sample to Use BOM

### ISSUE THREAD

**Issue by csviri** [java-operator-sdk/java-operator-sdk#1432]
BOM was added laterly, we should show the usage in at least one of our samples.

**Comment by derlin** [comment]
Would be glad to take it for Hacktoberfest :)

**Comment by derlin** [comment]
May I kindly ask you to put the label [`hacktoberfest-accepted`](https://hacktoberfest.com/participation/#pr-mr-details) to the PR ? 
You may refuse of course, I am glad to contribute anyway :)

**Comment by csviri** [comment]
@derlin added, pls check if it is good this way :)

**Comment by derlin** [comment]
great, thank you @csviri !
