### ISSUE TITLE
How to define multiple Dependent Resources of the same type

### ISSUE THREAD

**Issue by andreaTP** [java-operator-sdk/java-operator-sdk#1473]
## Bug Report

Trying to define multiple `DependentResources` of the same type (same `class`), seems to trigger the reconciliation loop continuously.

#### What did you do?

Enabled a 3rd dependent resource (which is again a `Secret` like the first one).
https://github.com/andreaTP/bink8s/blob/0177a66e4b31225c0b5a91e5694e80a3d3127df4/src/main/java/io/bink8s/controller/ImageBuildController.java#L17-L35

#### What did you expect to see?

The resource should be handled autonomously.
Also it should probably be possible to discriminate the secondary resource here:
https://github.com/andreaTP/bink8s/blob/0177a66e4b31225c0b5a91e5694e80a3d3127df4/src/main/java/io/bink8s/controller/workflow/ImageBuildSecretExistsReadyCondition.java#L17
(based on the name?)

#### What did you see instead? Under which circumstances?

The reconcile loop is triggered continuously.

#### Environment

**Kubernetes cluster type:**
minikube

`$ Mention java-operator-sdk version from pom.xml file`

Quarkus SDK 4.0.1

`$ java -version`
11

I might be doing something wrong, but I'm not sure how to debug it.

**Comment by csviri** [comment]
thx for the issue, however this is a duplicate:
This is a duplicate: https://github.com/java-operator-sdk/java-operator-sdk/issues/857

see also related PR with discriminators: 
https://github.com/java-operator-sdk/java-operator-sdk/pull/1378

**Comment by andreaTP** [comment]
You are right @csviri , closing as duplicate.
