### ISSUE TITLE
Extend documentation on DependentResources/Workflows

### ISSUE THREAD

**Issue by andreaTP** [java-operator-sdk/java-operator-sdk#1476]
The documentation regarding `DependentResource`s and `Workflow`s is pretty minimal and focuses on very very few examples close to "hello world".
It would be nice to see more extensive examples covering more "real-world-like" use cases.

Especially speaking about `Workflow` a lot of combinations/variations of the possible configurations are left to the user's imagination and reading the source code.

**Comment by grossws** [comment]
Also current docs have some obvious typos like `Reconsiler` and `Cleaner` for different CRDs, there's no source for conditions etc.

```java
@ControllerConfiguration(dependents = {
    @Dependent(name = DEPLOYMENT_NAME, type = DeploymentDependentResource.class,
        readyPostcondition = DeploymentReadyCondition.class),
    @Dependent(type = ConfigMapDependentResource.class,
        reconcilePrecondition = ConfigMapReconcileCondition.class,
        deletePostcondition = ConfigMapDeletePostCondition.class,
        dependsOn = DEPLOYMENT_NAME)
})
public class SampleWorkflowReconciler implements Reconciler<TestCustomResource>,
    Cleaner<WorkflowAllFeatureCustomResource> {
  // ...
}
```

**Comment by csviri** [comment]
thx @grossws , fixed here: https://github.com/java-operator-sdk/java-operator-sdk/pull/1568
