### ISSUE TITLE
Clear Approach How Do We Prefer Configuring Dependent Resources - Behavior and Properties

### ISSUE THREAD

**Issue by csviri** [java-operator-sdk/java-operator-sdk#1511]
Currently there could be two approaches to take how to specify some behavior / properties of a Dependent Resource. One is to specify it as a property, or implement it as an interface. To see on concrete example, the discriminator here is a property:

https://github.com/java-operator-sdk/java-operator-sdk/blob/9c1be9d59151f1673b5b2a5bea60543021fabd34/operator-framework/src/test/java/io/javaoperatorsdk/operator/sample/multiplemanageddependentsametype/MultipleManagedDependentResourceConfigMap2.java#L15-L16

While we set a SecondaryToPrimary mapper for a dependent resource, by implementing an interface:

https://github.com/java-operator-sdk/java-operator-sdk/blob/9c1be9d59151f1673b5b2a5bea60543021fabd34/operator-framework/src/test/java/io/javaoperatorsdk/operator/sample/primaryindexer/DependentPrimaryIndexerTestReconciler.java#L33-L34

we should clearly define how to and when to use an approach.

## Notes

The result of this issues should be an ADR (But let's agree on guidlines) , also the adjustment to the implementation of any.

**Comment by metacosm** [comment]
IMO, everything that can be set on a generic object should be a property so that you don't need to create an implementation just to change one thing. Anything that's central to how the dependent works should probably be implemented as an interface… So the distinction would be made on behavior as opposed to something that is more a "using" relationship (i.e. difference between inheritance and composition).

**Comment by csviri** [comment]
> IMO, everything that can be set on a generic object should be a property so that you don't need to create an implementation just to change one thing. Anything that's central to how the dependent works should probably be implemented as an interface… So the distinction would be made on behavior as opposed to something that is more a "using" relationship (i.e. difference between inheritance and composition).

On the other hand we could say that the `trait` (C(R)UD) interfaces could be modelled also as a property. 

But we can live with this definition. Basically then the `Deleter`, `Updater`, `Creator`, `BulkDependentResource`, `DependentResourceWithExplicitState` should be interfaces.

But `GenericResourceFetcher` should be rather a property instead of implemented by the dependent resource?

https://github.com/java-operator-sdk/java-operator-sdk/blob/2cb616c4c4fd0094ee6e3a0ef2a0ea82173372bf/operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/dependent/external/PollingDependentResource.java#L13-L13

**Comment by csviri** [comment]
Will close this issue for now, not sure if we should refactor anything now, but at least we will take this in mind in the future.
