### ISSUE TITLE
AbstractDependentResource reconciles two times on update

### ISSUE THREAD

**Issue by psemeniuk** [java-operator-sdk/java-operator-sdk#1535]
#### What did you do?

I created Reconciler on primary resource and CRUDKubernetesDependentResource connected with it. On the next step i triggered reconciliation which should update dependent resource. 

#### What did you expect to see?

Single call of `desired` method

#### What did you see instead? Under which circumstances?

Two calls of `desired` method - second is redundant.

#### Additional context

After analysis i assume the root cause is [HERE](https://github.com/java-operator-sdk/java-operator-sdk/blob/0d57629830cdd9ac1c3665438a1493ca438afdc4/operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/dependent/AbstractDependentResource.java#L47). The `desired` method is called here even if Optional returned from `computedDesired` has value. It's a pretty common mistake during using optionals, that `orElse` is called instead of `orElseGet` when we really need lazy evaluation.

#### Possible Solution

Just make `desired` call lazily evaluated by using `orElseGet` ;) 

#### Environment
`$ Mention java-operator-sdk version from pom.xml file`

3.1.1

**Comment by metacosm** [comment]
Indeed! 🤦🏼
