### ISSUE TITLE
operator is not triggered on changes of resource

### ISSUE THREAD

**Issue by warmuuh** [java-operator-sdk/java-operator-sdk#1569]
## Bug Report

operator is not triggered on changes of resource.

#### What did you do?

when i run my operator in an k8s cluster, it receives and acts on a resource right-away. But when i then change something on the resource, nothing happens. Only when i then manually restart (delete pod) the operator, it is triggered once. This happens only when i run the operator inside k8s.

#### What did you expect to see?

the operator should react on every change of the operated resource

#### What did you see instead? Under which circumstances?

when testing the operator against minikube, all is fine. when running it in our k8s cluster (which also uses RBAC) then things only work on start once. the operator doesnt seem to be notified for new events. What i DO see though is this warning during startup:

```
{"@timestamp":"2022-10-24T09:39:08.794Z","@version":"1","level":"WARN","severity":"WARN","logger_name":"io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager","thread":"OkHttp https://10.43.0.1/...","message":"Exec Failure: HTTP 403, Status: 403 - Forbidden","application":"my-crd-operator"}  
│ {"@timestamp":"2022-10-24T09:39:08.795Z","@version":"1","level":"DEBUG","severity":"DEBUG","logger_name":"io.fabric8.kubernetes.client.dsl.internal.AbstractWatchManager","thread":"OkHttp https://10.43.0.1/...","message":"Force closing the watch io.fabric8.kubernetes.client.dsl.internal.WatchConnectionManager@3acd530d","application":"my-crd-operator"}   
│ {"@timestamp":"2022-10-24T09:39:08.795Z","@version":"1","level":"DEBUG","severity":"DEBUG","logger_name":"io.fabric8.kubernetes.client.informers.impl.cache.Reflector","thread":"OkHttp https://10.43.0.1/...","message":"Watch gracefully closed for url.de/v1/my-crd","application":"my-crd-operator"}         
```
#### Environment

**Kubernetes cluster type:**

rancher

`$ Mention java-operator-sdk version from pom.xml file`
```xml
      <groupId>io.javaoperatorsdk</groupId>
      <artifactId>operator-framework-spring-boot-starter</artifactId>
      <version>3.2.0</version>
```

`$ java -version`

17

`$ kubectl version`

Client Version: v1.25.3
Kustomize Version: v4.5.7
Server Version: v1.20.8

#### Possible Solution

maybe some additional roleBindings necessary?

**Comment by csviri** [comment]
@warmuuh could you share some code to reproduce this?

This is highly unlikely, see our End To End tests, which are deployed to a cluster and are receiving the events. Maybe could you try also those?

**Comment by warmuuh** [comment]
yes...just learned about the `watch` permission.thx
