### ISSUE TITLE
Putting back event for reprocessing after a specific amount of time

### ISSUE THREAD

**Issue by csviri** [java-operator-sdk/java-operator-sdk#157]
We should allow users to put back events for reprocessing, this will allow periodic checking / polling with a very generic way.

**Comment by csviri** [comment]
We will cover this functionality within this issue:
https://github.com/ContainerSolutions/java-operator-sdk/issues/179

**Comment by goldmann** [comment]
Is the proposal here related to extending the `UpdateControl` class so that we could specify a time after which the event would be handled again?

Similarly to this: https://godoc.org/sigs.k8s.io/controller-runtime/pkg/reconcile#Result ?

**Comment by csviri** [comment]
@goldmann basically yes,  the issue mentioned before will cover this, but with a slightly different approach.

**Comment by goldmann** [comment]
@csviri Great, this is something I'm really interested in! I'll take a look at the PR.

**Comment by csviri** [comment]
@goldmann it's a quibe big PR, covering a log. Will write a post that will serve as a introduction / documentation to it. Also feel free to jump on discord and ask question if needed.
