### ISSUE TITLE
Inconsistent additionalPrinterColumns jsonPath 

### ISSUE THREAD

**Issue by lburgazzoli** [java-operator-sdk/java-operator-sdk#1631]
#### What did you do?

I have a class defined like:

```java
@JsonInclude(JsonInclude.Include.NON_NULL)
@Buildable(builderPackage = "io.fabric8.kubernetes.api.builder")
public class DeploymentSpec {

    @PrinterColumn(name = "CONNECTOR_TYPE_ID")
    private String connectorTypeId;
}
```

And such class is used in bot the `spec` and the `status` of a resource.

#### What did you expect to see?

The generated CRD should  always use the same path to describe the `CONNECTOR_TYPE_ID` column.

#### What did you see instead? Under which circumstances?

The resulted CRD may get amended at every build, i.e:

![image](https://user-images.githubusercontent.com/1868933/203999334-3cdf931f-b8a0-457a-9e46-bada27be0279.png)

#### Environment

Versions:

```xml
        <kubernetes-client.version>5.12.3</kubernetes-client.version>
        <java-operator-sdk.version>3.1.1</java-operator-sdk.version>
        <quarkus.version>2.11.2.Final</quarkus.version>
        <quarkus-operator-sdk.version>4.0.1</quarkus-operator-sdk.version>
        <sundrio.version>0.50.2</sundrio.version>
```

**Comment by csviri** [comment]
Hi @lburgazzoli if not obection, will transfer this issue to fabric8 client repo, since that functionality is implemented there.

**Comment by csviri** [comment]
@lburgazzoli could you pls move this issue  (re-create) in fabric8 client, this is implemented there. Thx!

**Comment by lburgazzoli** [comment]
Moved here: https://github.com/fabric8io/kubernetes-client/issues/4610
