### ISSUE TITLE
errors：trying to send message larger than max(2179626 vs. 2097152)

### ISSUE THREAD

**Issue by wangchenglonggithub** [java-operator-sdk/java-operator-sdk#1634]
I have an error message:
i.joperator.processing.eventDispatcher: Kubernets exception 500 failure eecyting :PUT at http://xxx .message: rpc error :code =trying to send message larger max(2179622 vs. 2097152)

I did not find the configuration item to solve the problem

Please help me

**Comment by csviri** [comment]
Hi @wangchenglonggithub , this issue seems to me a generic one with Kubernetes API server. 
probably the best place to ask is the `sig-api-machinery` channel on Kubernetes Slack.
see:
https://kubernetes.slack.com/archives/C0EG7JC6T/p1669669822416379

**Comment by csviri** [comment]
will close this for now. @wangchenglonggithub pls let us know if you found out the problem.
