### ISSUE TITLE
Generate project skeleton with CLI application

### ISSUE THREAD

**Issue by adam-sandor** [java-operator-sdk/java-operator-sdk#164]
The skeleton should include:
* Choice of app framework (Quarkus or Spring Boot)
* Healthcheck endpoint
* Dockerfile
* Kubernetes Deployment yaml
* CRD
* Operator and Controller classes
* RBAC definition file

All files should be templated with the name of the Operator and maybe some additional parameters.

This will be the base for a Kubebuilder plugin that will call the CLI (https://master.book.kubebuilder.io/reference/cli-plugins.html)

**Comment by psycho-ir** [comment]
I would suggest creating a new repository for this project. 
I can do it if there is no objection. 
Would be good to find a short and catchy name for the CLI binary too.

**Comment by adam-sandor** [comment]
I agree it should be a new repo.

As for catchy name it's tricky because it will do more than just the skeleton generation (e.g. class generation or yaml generation for CRD). I'm thinking something pretty generic like `josdk-cli`. The executable could be called `josdk`. Other ideas `jop` `javaop` `joperator`

**Comment by psycho-ir** [comment]
Here is the repo: 
https://github.com/java-operator-sdk/josdk-cli 

I'll prepare the skeleton of the project and most probably a prototype soon.

**Comment by wtrocki** [comment]
CLI written in java would be good but will have one disadvantage. When building CLI in golang it could be:

- Relying on existing tooling available in the kubebuilder and operator SDK
- Could be possibly included into Operator-SDK making java operator more discoverable (One CLI to rule them all)


On the bad side - there will be fewer tools to deal with the specifics of the Java/XMl code generation if that would be needed.

I have written numerous CLI's. If the target would be to just assemble the project we can get something very fast (like CLI done in 2 hours) and compile to native code using Node.js (https://github.com/aerogear/OpenVolunteerPlatform/tree/master/cli)

If the target would be much wider - simulate cases from the Operator-SDK-CLI then java might be much better

**Comment by adam-sandor** [comment]
Thanks for the input @wtrocki but I'm not convinced. I think it has more benefit to keep everything related to the java-operator-sdk in Java, otherwise we'll have components that a large part of the team doesn't touch because it's too much overhead to get into Golang to do so. Java has all the tools we need to create a CLI plus things like class generation from OpenAPI schemas we can leverage, so I don't feel like we're missing out on something.

As for Operator-SDK integration - the Operator-SDK team themselves told us to feel free to develop a CLI in Java and it will be possible to wrap it in a thin Golang wrapper to make it an official part of the Operator-SDK.

**Comment by wtrocki** [comment]
+100. Sorry for offtopic

**Comment by adam-sandor** [comment]
Don't say sorry, all suggestions are welcome!

**Comment by jmrodri** [comment]
Consider using the java-operator-plugins to get project scaffolding. https://github.com/operator-framework/java-operator-plugins/
