### ISSUE TITLE
withCustomResourcePredicate and withOnUpdateFilter don't work

### ISSUE THREAD

**Issue by bachmanity1** [java-operator-sdk/java-operator-sdk#1644]
I'm trying to use `withCustomResourcePredicate` to filter out some events for that I use code shown below:

```
operator.register(
        reconciler,
        configOverrider -> {
          configOverrider.withCustomResourcePredicate(
              (Controller<CusRes> controller, CusRes oldResource, CusRes newResource) -> {
                if (newResource == null || oldResource == null) {
                  return true;
                }
                if (someCondition) {
                  logger.info("withCustomResourcePredicate returns false");
                  return false;
                }
                logger.info("withCustomResourcePredicate returns true");
                return true;
              });
        });
```

I can see the message `withCustomResourcePredicate returns false` printed in the logs which means that the predicate returns `false` however the operator still reconciles the event. The same happens when I try to use `withOnUpdateFilter`. Is it a bug or am I doing something wrong? Thanks in advance.

**Comment by metacosm** [comment]
Which version of the SDK are you using? Note that `withCustomResourcePredicate` is deprecated, it might be that it is broken in more recent versions…

**Comment by bachmanity1** [comment]
I'm using `4.1.1`. If it was deprecated, what has replaced it? Is `withOnUpdateFilter` deprecated too because it also seems not to work?

**Comment by csviri** [comment]
There is an integration test for this, doubt it's not working:
https://github.com/java-operator-sdk/java-operator-sdk/blob/1ec4d7c186974b52582f3ea72c27514e7a66034c/operator-framework/src/test/java/io/javaoperatorsdk/operator/FilterIT.java#L29-L29

**Comment by csviri** [comment]
First you don't have to check explicitly the generation, that should be work out of the box (if you don't cancel it).

On startup is reconciled since what you get on that case is an ADD event. However it is a common practice to reconcile on startup. 
So I assume if you add an `onAddFileter` it should behave as you expect.

**Comment by csviri** [comment]
if you could create a simple open source operator to reproduce what exactly, that would help. It's hard to find out like this what exactly :)
