### ISSUE TITLE
Build Native Image using Quarkus

### ISSUE THREAD

**Issue by adam-sandor** [java-operator-sdk/java-operator-sdk#166]
Build a tiny Go-like Docker image using Quarkus native build. This will require us making the framework adhere to the GraalVM limitations.

**Comment by metacosm** [comment]
Should this be closed now?

**Comment by cortex93** [comment]
With 1.7.1, I must annotate my Spec and Status class with @RegisterForReflection. If not, jackson complains when deserializing.

**Comment by metacosm** [comment]
@cortex93 yes, this issue is already fixed in https://github.com/java-operator-sdk/java-operator-sdk/pull/311

**Comment by wtrocki** [comment]
I'm trying currently native builds. Is there any documentation/example (steps that we need in SDK itself) apart from following typical quarkus native build guide?

**Comment by metacosm** [comment]
@wtrocki the only thing you should need is `mvn package -Pnative`.

**Comment by metacosm** [comment]
@wtrocki the only thing you should need is `mvn package -Pnative`.

**Comment by jmrodri** [comment]
Using the quarkus extension `mvn package -Pnative` works for it. And there is another issue that covers building images: issue #96
