### ISSUE TITLE
Use polling strategy for custom resources

### ISSUE THREAD

**Issue by jmformenti** [java-operator-sdk/java-operator-sdk#1668]
Besides receive an event when a Custom resource is created/updated, is it possible for the same operator polling all the related custom resources each X seconds?

**Comment by csviri** [comment]
Hi @jmformenti  not sure if understand the question, but if you want to watch related custom resources, the `InformerEventSource` is all about that, it works exactly the same as with any Kubernetes resources. See the Tomcat Operator sample where it is actually used for custom resources.

**Comment by jmformenti** [comment]
Thanks for the reply, maybe what I'm looking for is the `PollingEventSource` in my case but I'm not sure.
Let me explain better.
I have a reconciler for Custom Resources of kind A, by default the reconciler is called when some CR of kind A is created or updated, that's perfect.
But in addition, I would like to call the reconciler for each CR of kind A every X seconds (in other words, poll the kind A resources every X seconds).
How can this be implemented?

**Comment by csviri** [comment]
https://javaoperatorsdk.io/docs/features#using-updatecontrol-and-deletecontrol

`UpdateControl.rescheduleAfter(..)` will do the job.

**Comment by csviri** [comment]
@jmformenti hope this answers the question, if no objection will close this issue. (Will reopen in case needed)

**Comment by jmformenti** [comment]
Thanks a lot for the response! sorry for not commenting earlier It was very useful :+1:
