### ISSUE TITLE
Integrate with Operator Lifecycle Manager (OLM)

### ISSUE THREAD

**Issue by adam-sandor** [java-operator-sdk/java-operator-sdk#167]
Red Hat is heavily pushing OLM as the next gen deployment mechanism for operators (which in turn would be the next gen deployment mechanism for applications). We could integrate with OLM (whatever that means exactly).
I already checked that using the operator-sdk isn't a prerequisite for OLM integration, so we should be good to go.

https://github.com/operator-framework/operator-lifecycle-manager

**Comment by csviri** [comment]
Totally agree with @derlin . I think @adam-sandor created this issue , before there was the Operator SDK integration implemented. Will close this issue if not objections.

**Comment by metacosm** [comment]
Thank you for the investigation. We don't currently plan to support OLM at the JOSDK level but perhaps it would make sense to document this?
