### ISSUE TITLE
How to create multiple services using CRUDKubernetesDependentResource

### ISSUE THREAD

**Issue by prateekkohli21** [java-operator-sdk/java-operator-sdk#1684]
I am using JOSDK version 4.0.0.

I need to create 3-4 dependent(secondary) services based on a primary resource.

I am unable to figure out how can I do it using CRUDKubernetesDependentResource.

Using the below code, I would be able to return just 1 service from the desired method, what if I need to create 3 services?
Would it be possible using CRUDKubernetesDependentResource?

public class ServiceDependentResource extends CRUDKubernetesDependentResource<Service, CustomService> {

    public PerBrokerServiceDependentResource(Class<Service> resourceType) {
        super(resourceType);
    }

    @Override
    protected Service desired(CustomService customService, Context<CustomService> context) {
        
    }

**Comment by silenium-dev** [comment]
There is an interface called `BulkDependentResource` which can be used with `KubernetesDependentResource`.
You could give it a try and see if it works with `CRUDKubernetesDependentResource`.

See also:
- [docs](https://javaoperatorsdk.io/docs/dependent-resources#bulk-dependent-resources)
- [example](https://github.com/java-operator-sdk/java-operator-sdk/blob/f5ffcfb6f546d79b4bab04ea503c8bad9d6acce6/operator-framework/src/test/java/io/javaoperatorsdk/operator/sample/bulkdependent/ConfigMapDeleterBulkDependentResource.java)

**Comment by prateekkohli21** [comment]
But I am on version 4.0.0 & I think BulkDependentResource is not present on this version.

Is there any other way of doing it on the older version?

**Comment by csviri** [comment]
There is no explicit support for this on other versions and not trivial to hack it there. Although you can always implement you own implementation just based on the `DependentResource` interface.

**Comment by silenium-dev** [comment]
> But I am on version 4.0.0 & I think BulkDependentResource is not present on this version.
> 
> Is there any other way of doing it on the older version?

Are you able to update to 4.2.0 or is this an external limitation (e.g. by your company)?

**Comment by prateekkohli21** [comment]
> > But I am on version 4.0.0 & I think BulkDependentResource is not present on this version.
> > Is there any other way of doing it on the older version?
> 
> Are you able to update to 4.2.0 or is this an external limitation (e.g. by your company)?

Yes, because of company limitation I won't be able to update to latest version.

**Comment by csviri** [comment]
@prateekkohli21 an alternatrive would be to not use dependent resource just the low level API. 

(Or update in the future if that will be allowed).

For now will close this issue, if that is ok with you all. Hope everything is clarified.
