### ISSUE TITLE
Finalizer of old resource is not removed after updating from 4.1.2 to 4.2.0/4.2.1

### ISSUE THREAD

**Issue by popdaniel942** [java-operator-sdk/java-operator-sdk#1692]
If I create a resource while using operator 4.1.2 and then I update the operator to 4.2.1 and I try to delete the previously created resource, the cleanup code is being called and it ends with a DeleteControl.defaultDelete() but the resource itself does not get deleted, it just hangs. The finalizer is still there and if I remove it manually, it gets deleted. And if I recreate the resource with 4.2.1, I can delete it just fine. If I revert the operator version to 4.1.2 while the resource hangs in deletion, it will get deleted automatically. If I create a resource while on version 4.2.1 and I revert to 4.1.2, I can delete it with no problems. The problem appears only when going from 4.1.2 to 4.2.1.
Unfortunately there is nothing in the logs other than my own logs from the cleanup method. It's like everything is fine but the finalizer is not removed.

**Comment by csviri** [comment]
After investigation this is caused by the modification that we made to remove finalizers with Server Side Apply, because of an experimental feature of pruning resources in the cache. Since the usefulness of that feature is questionable at this point, will rather remove it and revert back the finalizer removal too, that will solve this problem.

**Comment by metacosm** [comment]
> After investigation this is caused by the modification that we made to remove finalizers with Server Side Apply, because of an experimental feature of pruning resources in the cache. Since the usefulness of that feature is questionable at this point, will rather remove it and revert back the finalizer removal too, that will solve this problem.
> 
> cc @metacosm

I agree.
