### ISSUE TITLE
Error in GenericKubernetesResourceMatcher when reconciling resources with no spec

### ISSUE THREAD

**Issue by harveyelsom** [java-operator-sdk/java-operator-sdk#1715]
#### What did you do?

created a ServiceAccount as a dependent resource.

#### What did you expect to see?

The Service account being correctly reconciled

#### What did you see instead? Under which circumstances?

Caused by: java.lang.NoSuchMethodException: io.fabric8.kubernetes.api.model.ServiceAccount.getSpec()
        at java.base/java.lang.Class.getMethod(Class.java:2277)
        at io.javaoperatorsdk.operator.ReconcilerUtils.getSpec(ReconcilerUtils.java:98)
        ... 25 more

#### Possible Solution

Stack trace suggests this is the problem https://github.com/java-operator-sdk/java-operator-sdk/blob/main/operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/dependent/kubernetes/GenericKubernetesResourceMatcher.java#L61 
A kubernetes ServiceAccount does not have a spec but this generic matcher will always try to getSpec().

I expect this would fail for other resources that don't have a Spec.

I suspect I can override the matcher to get past this but the GenericKubernetesResourceMatcher shouldn't be failing like this.

**Comment by csviri** [comment]
Hi @harveyelsom , yes you can override the matcher for now.

However would be nice to provide a matcher that is out of the box (we already to for ConfigMap and Secret ), so would classify this as an improvements. And will do probably for 4.3.

**Comment by juangon** [comment]
Yes, I have ServiceAccount dependent resources too, just had to implement `Matcher` interface: 
```java
@Override
    public Result<ServiceAccount> match(ServiceAccount actual, PrimaryResource primary, Context<PrimaryResource> context) {

        return Result.nonComputed(
            actual.getMetadata().getName().equals("my-sa") &&
            actual.getMetadata().getNamespace().equals(primary.getMetadata().getNamespace()));
    }
```

**Comment by csviri** [comment]
Yep, however not sure if it makes sense to compare the name and namespace, rather other data like:
`imagePullSecrets` , `automountServiceAccountToken`, ...

**Comment by csviri** [comment]
Added a PR, but in pure equality cases might be just enough to override the `equals` method on spec and use that in the matcher.
