### ISSUE TITLE
Dependent Subresource Management

### ISSUE THREAD

**Issue by adam-sandor** [java-operator-sdk/java-operator-sdk#173]
If the operator creates new Kubernetes resources, it usually has to track their lifecycle by listening to their events. This is currently very cumbersome with having to create lots of watches manually.

* Hard to create the watches - what if the operator get's restarted after the watches were created?
* When the watch fires it can't update the custom resource easily.

**Comment by csviri** [comment]
Yep, we definitely need to solve this within the framework. Probably we shouldn't call it as sub-resources since its already marks something else in k8s, maybe operator "managed resources"?
Already designed something, maybe we should take a look on a refinement meeting.

**Comment by csviri** [comment]
See: https://github.com/ContainerSolutions/java-operator-sdk/issues/179
This will cover this functionality.
