### ISSUE TITLE
Support graceful stop with configurable timeout

### ISSUE THREAD

**Issue by gyfora** [java-operator-sdk/java-operator-sdk#1730]
## Feature Request

It would be great if we could support a graceful stop/shutdown operation that would wait for currently in progress reconciliation for a user configured timout period.

During the shutdown we should not trigger new reconciliation.

This would also allow a smoother operation during upgrades, or other pod restarts.

**Comment by metacosm** [comment]
Unless I'm mistaken, we already have something like this: https://github.com/java-operator-sdk/java-operator-sdk/blob/main/operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/config/ConfigurationService.java#L126, which you can configure using: https://github.com/java-operator-sdk/java-operator-sdk/blob/main/operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/config/ConfigurationServiceOverrider.java#L63 prior to starting your operator.

**Comment by csviri** [comment]
Ahh, yes, but for this I think the shutdown hook is needed. That is deprecated. Probably it should not be then.

**Comment by csviri** [comment]
Also would be good to have an integration test for this.

**Comment by metacosm** [comment]
You need a shutdown hook to be able to handle graceful shutdowns, though, don't you?
