### ISSUE TITLE
Configurable collection of metrics

### ISSUE THREAD

**Issue by sorend** [java-operator-sdk/java-operator-sdk#1750]
Hi.

In issue #1324 metrics at the resource level were added. The result is ~80 metrics per resource.

We have a controller which reconciles resources in the count of 10k+, and while the rest of the framework is excellent for us, the amount of metrics collected is quite unmanageable.

Would it be possible to make the per-resource collection of metrics optional through configuration?

Thanks,
Soren

**Comment by csviri** [comment]
Hi @sorend ,

you can have your own metrics implementation, by overriding the interface:

https://github.com/java-operator-sdk/java-operator-sdk/blob/main/operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/monitoring/Metrics.java

`Operator operator = new Operator(client, o -> o.withMetrics(new MyMetricsImplementation()));`

And you can just ignore some callbacks. 

Do I understand correctly, that this should solve your problem?

**Comment by metacosm** [comment]
It might indeed be easier to create a new metrics implementation than provide the support to configure the existing one.

**Comment by sorend** [comment]
I am using java-operator-sdk through Quarkus, but I see your point, and I will try to go ahead with it, thanks.

**Comment by csviri** [comment]
kk, if you have any suggestions, or improvements pls let us know, or create a PR, would be very helpful. Will close this issue for now.

**Comment by metacosm** [comment]
> I am using java-operator-sdk through Quarkus, but I see your point, and I will try to go ahead with it, thanks.

Please let me know if you encounter any issue with the Quarkus extension in this respect.

**Comment by metacosm** [comment]
Just took a brief look and this might indeed not be as easy as it should be. I've opened https://github.com/quarkiverse/quarkus-operator-sdk/issues/504 to improve this aspect.
