### ISSUE TITLE
Extend UpdateConrol to be able to patch CustomResource (?)

### ISSUE THREAD

**Issue by csviri** [java-operator-sdk/java-operator-sdk#1763]
Currently with [UpdateControl](https://github.com/java-operator-sdk/java-operator-sdk/blob/dda3a10b63cbe083f1a14af1e8d896e915eff5f7/operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/reconciler/UpdateControl.java#L6-L6) we are able to update the resource (with optimistic locking). 

Should we add possibilities to patch the custom resource without optimistic locking, (also a version that patches both the resource and the status)?

Usually at the end of a reconciliation the status of a custom resource is updated. In some cases however some parts of the resource are altered too. Typically we see that users add labels or annotations to metadata of the resource.
It might happen however that users do some subsequent logic on the next reconciliation based on this change.

If the update is done by `UpdateControl.update` the framework guarantees that for the next reconciliation the updated resource will be passed to the reconciler. However we are able to guarantee this only if the resource is updated using optimistic locking (emitting the details, generally this is not possible to do this correctly without optimistic locking).

Back to the original question, should we support patch without optimistic locking? In this case might happen that for next reconciliation the reconciler won't receive the update resource, but a previous version of it. So if the reconciliation implementation logic requires strict consistency (in terms that receives always the up to date CR if such cases, so there is casual dependency) this can result in problems - although this probably is rather an exotic case.

Note that users already can do such updates using directly the client, before the reconciliation returns.

Ultimately IMHO it boils down to the question of an API design if we should encourage doing "always the correct approach" or give a possibility to users and just document it well what are the risks with other approaches.

**Comment by metacosm** [comment]
Such a feature looks tricky to support with our current internal model which expects to receive the latest version of the resource being reconciled. Relaxing this constraint might have too much of an impact on the rest of the SDK?

**Comment by csviri** [comment]
That is important only if the reconciliation logic depends on it. For example if a controller would add label, what would results that the controllers label selector won't select that resource anymore, it's a valid use-case. 
But strong consistency is requires just in some use cases, the reconciler should be idempotent, so even if it reconciles again the not most up-to date resource, so basically on previous one (or again on the last one that was already reconciled), would not necessary results in an error. This is necessary if there is only some casual dependency, so if an update like adding some label would have consequences on the logic executed in the reconciler.

So it's more like an optimization. 

Note that it has more meaning for secondary resources, where again it the next reconciliation it can make sure that it works with already updated resources. Eventually this might results in less reconciliation cycles.
