### ISSUE TITLE
Operator doesn't start on informer access error even if stopOnInformerError is set to False

### ISSUE THREAD

**Issue by gyfora** [java-operator-sdk/java-operator-sdk#1775]
## Bug Report

With `stopOnInformerError` set to false and watching 2 namespaces `default,ns1`, if I remove the rolebinding for ns1 access the operator won't start correctly.

We get the warn logs (` [WARN ] listSyncAndWatch failed for...`) but the `operator.start()` call does not return until we actually send an event to the other namespace (into `default` in my case). After that the start returns and the operator starts. (and as expected we continue to receive the warn logs for ns1)

#### What did you expect to see?

I would expect the operator to start even if the other watched but accessible namespaces do not have any resources in them.

#### Environment

Kind

**Comment by csviri** [comment]
thank you for reporting, will take a look soon!

**Comment by csviri** [comment]
Hi @gyfora , 
I create a related integration test, but was not able to reproduce the issue.

**Comment by gyfora** [comment]
Maybe this is specific to my local env somehow. I see now that it actually starts but sometimes takes a few minutes... strange.
