### ISSUE TITLE
Stability of generated csv

### ISSUE THREAD

**Issue by shawkins** [java-operator-sdk/java-operator-sdk#1791]
## Bug Report

Logic has been added to generate our bundle https://github.com/bf2fc6cc711aee1a0c2a/kas-fleetshard/tree/main/bundle and we're seeing that the generated csv is not stable.

#### What did you expect to see?

Stable csv

#### What did you see instead? Under which circumstances?

We have 2 crds, the owned crds may be listed in either order.  We are creating the Deployments via quarkus integration and providing env variables via the application.properties.  The env variable ordering also seems to not be stable.

#### Environment

Quarkus operator extension 4.0.7

**Comment by andreaTP** [comment]
I think that this issue belongs to: https://github.com/quarkiverse/quarkus-operator-sdk

**Comment by metacosm** [comment]
Yes.
