### ISSUE TITLE
CRD generator driven off of field names

### ISSUE THREAD

**Issue by shawkins** [java-operator-sdk/java-operator-sdk#1792]
## Bug Report

The CRD generator seemed to ignore accessor methods and just used the field name.

#### What did you do?

With a class like

```
@Getter
@Setter
@Accessors(prefix = "_")
public class Foo {
    private boolean _field;
}
```

The generated crd contained _field, rather than field as the property name.

#### Environment

Quarkus operator extension 4.0.7

#### Possible Solution

The workaround was to add a JsonProperty to the field.

**Comment by metacosm** [comment]
Closed in favor of https://github.com/fabric8io/kubernetes-client/issues/4934.
