### ISSUE TITLE
CRD is not getting updated for feild

### ISSUE THREAD

**Issue by Akash47** [java-operator-sdk/java-operator-sdk#1794]
#### What did you do?

    We are trying to update the field in our CRD but while doing that we seeing error from java-operator sdk . To understand this issue in better way. I am attaching logs.

#### What did you expect to see?

CRD should update properly.

#### What did you see instead? Under which circumstances?
<img width="1319" alt="logs" src="https://user-images.githubusercontent.com/16708883/222641808-da851456-06eb-4c0f-9567-a1edd549c801.png">

#### Environment

**Kubernetes cluster type:**

kubernetes

`$ Mention java-operator-sdk version from pom.xml file` -> 

  1.9.7

`$ java -version` 

open jdk 11

`$ kubectl version`

1.19.9

**Comment by metacosm** [comment]
Can you please attach more complete logs in text format?
1.9.7 is really old and we don't support it anymore. Isn't upgrading to a more recent version an option?

**Comment by Akash47** [comment]
Thanks for response.  I have attached the text logs. Migration will be difficult for us before that we want understand problem and based on that we select version and move on to that.
[log.log](https://github.com/java-operator-sdk/java-operator-sdk/files/10943548/log.log)

**Comment by metacosm** [comment]
It's difficult to tell only from these logs what's going on as the only thing that we can see is that the retries somehow got exhausted for that particular CR but without anymore information as to what might have caused the retries in the first place. Could you increase the logging level and provide more complete logs, please?
