### ISSUE TITLE
Can I update the CR status during cleanup? 

### ISSUE THREAD

**Issue by dijkwxyz** [java-operator-sdk/java-operator-sdk#1875]
Dear community,
I'm using JOSDK 4.3.0 to develop an operator that drives a CR with a dependent resource. The dependent resource is from our business system. When I delete the CR, I need to delete the dependent resource first, so the deletion is async. I wish to update the CR's status during deletion because the clean-up contains many steps.
Is there a way I could achieve this? I checked the `Cleaner` interface but the DeleteControl doesn't seem to support updating the status. 
Any help would be appreciated!

Best regards.

**Comment by csviri** [comment]
Hi @dijkwxyz ,

yes you can just use the `KubernetesClient` and update the primary resource directly from within the code.

**Comment by csviri** [comment]
Client can be retrieved from the context, see:

https://github.com/java-operator-sdk/java-operator-sdk/blob/v4.3.0/operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/reconciler/Context.java#L34

**Comment by dijkwxyz** [comment]
Thank you. I really appreciate the help!
