### ISSUE TITLE
Improve handling of Custom Resource Client

### ISSUE THREAD

**Issue by adam-sandor** [java-operator-sdk/java-operator-sdk#199]
There are two problems with controller that want to modify their custom resource objects using the special client Fabric8 provides for these operations (MixedOperation interface).

1. The client gets created in the Operator using a somewhat complicated mechanism, and there is no good way to get hold of the client object in the controller.

2. The type of the client is horrific abomination of generics, so if I do manage to get it into the controller it looks like this: `private MixedOperation<Tomcat, CustomResourceList<Tomcat>, CustomResourceDoneable<Tomcat>, Resource<Tomcat, CustomResourceDoneable<Tomcat>>> tomcatOperations;`

One possible solution is to pass the client to the controller in the context object, which solves both problems. The downside is that controllers get the KubernetesClient passed in their constructor so it looks a bit weird to pass the custom resource client in the context.

**Comment by adam-sandor** [comment]
The workaround for the first problem is to pass the custom resource client to the Controller after it has been registered in the Operator, so the Operator has already created it. Surprisingly the Operator has a getter for these clients.

```
        KubernetesClient client = new DefaultKubernetesClient(config);
        Operator operator = new Operator(client);

        TomcatController tomcatController = new TomcatController(client);
        operator.registerControllerForAllNamespaces(tomcatController);
        tomcatController.setTomcatOperations(operator.getCustomResourceClients(Tomcat.class));
```

**Comment by metacosm** [comment]
Should this be closed now?
