### ISSUE TITLE
Adding Table of Content to Readme.md

### ISSUE THREAD

**Issue by ng29** [java-operator-sdk/java-operator-sdk#206]
Hey @adam-sandor / @csviri / @charlottemach 

What would you like to be added:

The idea for Adding Table of Content to Readme.md to add additional enhancement and readability to the docs file.

Why is this needed:

TOC is very useful to hop between the docs/info of the readme and avoids useless scrolling.

**Comment by pradipta** [comment]
Can I pick this up?

**Comment by kirek007** [comment]
Hi, table of content is already in place. Closing :)
