### ISSUE TITLE
Support only java version 11 and above! 

### ISSUE THREAD

**Issue by psycho-ir** [java-operator-sdk/java-operator-sdk#232]
As any projects that are going to use this SDK most probably would be from scratch I would suggest increasing the minimum supported Java version to **11**.

So that we can use new features defined till this version and encourage the teams to use the newer version of the Java!

**Comment by csviri** [comment]
Yep, I agree with this argument, that we are not supporting any legacy versions, since we are a new project. Why would it make sense to start developing an operator with Java 8. Absolutely true.

@adam-sandor @kirek007 any thoughts?

**Comment by kirek007** [comment]
100% agree. We can bump to min Java 11.

**Comment by psycho-ir** [comment]
Cool, I'll open a PR for it then.

**Comment by adam-sandor** [comment]
agreed, let's drop the support for 8
