### ISSUE TITLE
Using the CRD name if no finalizer is provided is not a good default

### ISSUE THREAD

**Issue by metacosm** [java-operator-sdk/java-operator-sdk#233]
Unfortunately, CRD names don't mandate that their group be a valid domain name, therefore using `<plural>.<group>/finalizer` is not guaranteed to be a valid finalizer name. 
Possible options for the first part of the finalizer identifier:
- FQN of the associated controller
- CR Kind + package name
- CR Kind / CR simple class name + `.javaoperatorsdk.io`

Tha last one being the less risky in terms of validation, though https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#finalizers doesn't specify that the finalizer id be a valid kubernetes name (which it isn't anyway because of the `/`) so we probably aren't constrained to only 63 characters length.

**Comment by psycho-ir** [comment]
@metacosm isn't this related to the validation that [openshift-client](https://github.com/fabric8io/kubernetes-client/blob/f4eea6e3a4164b0a47ae132cdf1190ef26101496/kubernetes-model-generator/kubernetes-model-core/src/main/java/io/fabric8/kubernetes/api/model/HasMetadata.java#L25) has?

I don't think the `tld` length needs to have a limit. The current max length of the `tld` is way higher than 6 (I think it's 24 or something already) and may **change** in future. 
So I would suggest to just ensure that the format and [the length of labels are valid](https://tools.ietf.org/html/rfc1035).

**Comment by metacosm** [comment]
> @metacosm isn't this related to the validation that [openshift-client](https://github.com/fabric8io/kubernetes-client/blob/f4eea6e3a4164b0a47ae132cdf1190ef26101496/kubernetes-model-generator/kubernetes-model-core/src/main/java/io/fabric8/kubernetes/api/model/HasMetadata.java#L25) has?

Indeed.

> I don't think the `tld` length needs to have a limit. The current max length of the `tld` is way higher than 6 (I think it's 24 or something already) and may **change** in future.
> So I would suggest to just ensure that the format and [the length of labels are valid](https://tools.ietf.org/html/rfc1035).

Right, good catch. Should a domain name end with an existing TLD? If yes, then many of the current CRD names that are defined in the code wouldn't be valid and therefore not appropriate as prefix for finalizer identifiers.

**Comment by psycho-ir** [comment]
> > @metacosm isn't this related to the validation that [openshift-client](https://github.com/fabric8io/kubernetes-client/blob/f4eea6e3a4164b0a47ae132cdf1190ef26101496/kubernetes-model-generator/kubernetes-model-core/src/main/java/io/fabric8/kubernetes/api/model/HasMetadata.java#L25) has?
> 
> Indeed.
> 
> > I don't think the `tld` length needs to have a limit. The current max length of the `tld` is way higher than 6 (I think it's 24 or something already) and may **change** in future.
> > So I would suggest to just ensure that the format and [the length of labels are valid](https://tools.ietf.org/html/rfc1035).
> 
> Right, good catch. Should a domain name end with an existing TLD? If yes, then many of the current CRD names that are defined in the code wouldn't be valid and therefore not appropriate as prefix for finalizer identifiers.

Existing TLDs are subject to change anytime, so I don't think it's reasonable to add them to the validation. 
Furthermore one can have their own DNS with any domain name follow the format but not ending with existing tlds.

**Comment by metacosm** [comment]
> Existing TLDs are subject to change anytime, so I don't think it's reasonable to add them to the validation.

Well, we could retrieve the TLD list from IANA at compile time and then… 😀 </overengineering>

> Furthermore one can have their own DNS with any domain name follow the format but not ending with existing tlds.

Good point. I will fix the validation code.

**Comment by metacosm** [comment]
This will be addressed at the fabric8 client level.
