### ISSUE TITLE
Can you provide redis-sentinel samples?

### ISSUE THREAD

**Issue by objcoding** [java-operator-sdk/java-operator-sdk#247]
Thanks to the author for providing java-operator-sdk, I now need an example of redis sentinel. The specific logic is that three sentinel nodes manage multiple sets of master-slave, and master-slave can be dynamically added and deleted according to the situation. I don’t know if the author can provide this example What? Greatful!

**Comment by csviri** [comment]
@objcoding I'm sorry but currently we don't have a bandwidth at this point of time.

**Comment by objcoding** [comment]
> @objcoding I'm sorry but currently we don't have a bandwidth at this point of time.

ok, thank you.

**Comment by adam-sandor** [comment]
I will close this issue as we wont be providing samples for specific technologies as samples are meant to demonstrate framework features. If you'd implement an operator for redis yourself @objcoding using the java-operator-sdk we're happy to help!
