### ISSUE TITLE
About the return value of the createOrUpdateResource method.

### ISSUE THREAD

**Issue by objcoding** [java-operator-sdk/java-operator-sdk#268]
After reading the source code, I found that if the createOrUpdateResource method throws a runtime exception, the event will be rescheduled. If it returns UpdateControl, the corresponding crd resource update will be performed according to the returned value.
So the question is, if I need to update the crd resource status and at the same time need to reschedule the event, what do I need to do?

**Comment by objcoding** [comment]
In the golang version of operator sdk, the Reconcile method has both Result and err return values. The Requeue value of Result is true or err != nil, and the event will be rescheduled.

**Comment by objcoding** [comment]
![image](https://user-images.githubusercontent.com/24354760/102854032-8c82e280-445c-11eb-93d7-472e13b1f2ac.png)

**Comment by objcoding** [comment]
Can it be understood that if the updateStatus or replace method is called to update the CustomResource, the Operator will receive events from the K8s Watch again?
If this is the case, then the user does not need to actively throw runtime exceptions in the Operator.

**Comment by csviri** [comment]
The update and rechedule can be done at the same time now using `UpdateControl`, not it extends [BaseControl](https://github.com/java-operator-sdk/java-operator-sdk/blob/main/operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/reconciler/BaseControl.java) what has the `rescheduleAfter` method in v2, but similar exists in v1.
