### ISSUE TITLE
MySQLSchema sample Custom Resource fails to delete

### ISSUE THREAD

**Issue by junglie85** [java-operator-sdk/java-operator-sdk#276]
The MySQL sample doesn't delete from my EKS cluster (v.1.18.x); I've used this sample as a basis for my operator, which equally doesn't delete.

```shell
❯ kubectl delete -f k8s/example.yaml
mysqlschema.mysql.sample.javaoperatorsdk "mydb" deleted
^C
```

Is this a problem anyone else has experienced with the sample? If so, what's the fix?

**Comment by jmrodri** [comment]
@ambye85 could this be finalizer related? Is the operator no longer running when you delete the example? Does this still happen?

**Comment by csviri** [comment]
Checked this, it works on the current `main`. Will close the issue.
