### ISSUE TITLE
CRD validation doesn't accept empty values for type "object" fields

### ISSUE THREAD

**Issue by objcoding** [java-operator-sdk/java-operator-sdk#286]
When the type of crd custom resource is object, if it is empty, an error will be reported as follows:

ZcacheCluster.com.zto.zcache "sentinel-1" is invalid: [spec.sentinel.config: Invalid value: "null": spec.sentinel.config in body must be of type object: "null", spec.redis.storage: Invalid value: "null": spec.redis.storage in body must be of type object: "null", spec.redis.config: Invalid value: "null": spec.redis.config in body must be of type object: "null", status: Invalid value: "null": status in body must be of type object: "null"]. Received status: Status(apiVersion=v1, code=422, details=StatusDetails(causes=[StatusCause(field=spec.sentinel.config, message=Invalid value: "null": spec.sentinel.config in body must be of type object: "null", reason=FieldValueInvalid, additionalProperties={}), StatusCause(field=spec.redis.storage, message=Invalid value: "null": spec.redis.storage in body must be of type object: "null", reason=FieldValueInvalid, additionalProperties={}), StatusCause(field=spec.redis.config, message=Invalid value: "null": spec.redis.config in body must be of type object: "null", reason=FieldValueInvalid, additionalProperties={}), StatusCause(field=status, message=Invalid value: "null": status in body must be of type object: "null", reason=FieldValueInvalid, additionalProperties={})], group=com.zto.zcache, kind=ZcacheCluster, name=sentinel-1, retryAfterSeconds=null, uid=null, additionalProperties={}), kind=Status, message=ZcacheCluster.com.zto.zcache "sentinel-1" is invalid: [spec.sentinel.config: Invalid value: "null": spec.sentinel.config in body must be of type object: "null", spec.redis.storage: Invalid value: "null": spec.redis.storage in body must be of type object: "null", spec.redis.config: Invalid value: "null": spec.redis.config in body must be of type object: "null", status: Invalid value: "null": status in body must be of type object: "null"], metadata=ListMeta(_continue=null, remainingItemCount=null, resourceVersion=null, selfLink=null, additionalProperties={}), reason=Invalid, status=Failure, additionalProperties={}).

**Comment by objcoding** [comment]
My crd：
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: zcacheclusters.com.zto.zcache
spec:
  group: com.zto.zcache
  scope: Namespaced
  names:
    plural: zcacheclusters
    singular: zcachecluster
    kind: ZcacheCluster
    shortNames:
      - zc
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        required:
        - spec
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
          spec:
            type: object
            required:
            - resourceType
            properties:
              resourceType: # sentinel or redis
                type: string
              sentinel: # sentinel 配置
                type: object
                properties:
                  replicas:
                    format: int32
                    type: integer
                    minimum: 3
                  container:
                    type: object
                    properties:
                      image:
                        type: string
                        default: redis:5.0.4-alpine
                      pullPolicy:
                        type: string
                        default: Always
                      resources:
                        type: object
                        properties:
                          limits:
                            type: object
                            properties:
                              cpu:
                                type: string
                              memory:
                                type: string
                          requests:
                            type: object
                            properties:
                              cpu:
                                type: string
                              memory:
                                type: string
                  config:
                    type: object
              redis: # redis 节点配置
                type: object
                properties:
                  replicas:
                    format: int32
                    type: integer
                    minimum: 2
                  sentinelName:
                    type: string
                  group:
                    type: string
                  container:
                    type: object
                    properties:
                      image:
                        type: string
                        default: redis:5.0.4-alpine
                      pullPolicy:
                        type: string
                        default: Always
                      resources:
                        type: object
                        properties:
                          limits:
                            type: object
                            properties:
                              cpu:
                                type: string
                              memory:
                                type: string
                          requests:
                            type: object
                            properties:
                              cpu:
                                type: string
                              memory:
                                type: string
                  storage:
                    type: object
                    properties:
                      emptyDir:
                        type: object
                      keepAfterDeletion:
                        type: boolean
                      persistentVolumeClaim:
                        type: object
                  config:
                    type: object
          status:
            type: object
            properties:
              conditions:
                items:
                  properties:
                    lastTransitionTime:
                      type: string
                    lastUpdateTime:
                      type: string
                    message:
                      type: string
                    reason:
                      type: string
                    status:
                      type: string
                    type:
                      type: string
                  required:
                    - type
                    - status
                  type: object
                type: array
              masterIP:
                type: string
              sentinelIP:
                type: string
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []

**Comment by metacosm** [comment]
Hi @objcoding, this doesn't really appear to be an issue with this project but rather a problem either with your CRD or your custom resources. Closing this for now. Please re-open if you feel that the sdk is somehow causing the issue.
