### ISSUE TITLE
Avoid having to define Quarkus version in addition to extension

### ISSUE THREAD

**Issue by adam-sandor** [java-operator-sdk/java-operator-sdk#291]
It's error prone to have to define both the version of the josdk I'm using as well as the Quarkus version for the Quarkus plugin. I'm not sure if it's possible but it would sure be great if the `quarkus-maven-plugin` version was somehow defined by the `operator-framework-quarkus-extension`.

**Comment by metacosm** [comment]
I'm pretty sure it's not feasible since maven dependencies cannot impact the set of plugins your build is configured with. Note that you have the same issue with Spring Boot and the Spring Boot starter.
