### ISSUE TITLE
Consider using GitHub action to format code on push

### ISSUE THREAD

**Issue by metacosm** [java-operator-sdk/java-operator-sdk#298]
A GitHub action is available to format the code on push: https://github.com/axel-op/googlejavaformat-action
This would allow us to automatically address format issues instead of failing the build for something sometimes as stupid as a wrong whitespace thus freeing developers to focus more on functionality instead of how their code looks like while maintaining a consistent style across the code base.

**Comment by adam-sandor** [comment]
I'm all for this. Local formatting only helps because you can see the results, but if the results suck you can't change them anyway. GH action taking care of this is a win.
