### ISSUE TITLE
Better automatically generated controller names?

### ISSUE THREAD

**Issue by metacosm** [java-operator-sdk/java-operator-sdk#301]
Very often a controller class will be named `SomethingController` or `SomethingResourceController`. We could trim these names to remove the redundant `Controller` or `ResourceController` part so that they feel more natural when referring to the controller in configuration files. Another option would be to use the associated Custom Resource name / kind as the default name for the controller. /cc @adam-sandor @psycho-ir

**Comment by adam-sandor** [comment]
Hmm.. I don't know. The class itself would look weird without the suffix. And it may cause problems with naming the CR. For example I have a class Tomcat for the CR and related TomcatController.

**Comment by metacosm** [comment]
> Hmm.. I don't know. The class itself would look weird without the suffix. And it may cause problems with naming the CR. For example I have a class Tomcat for the CR and related TomcatController.

The name of the class wouldn't change, just the name that is used to refer to the controller in the configuration. In the above example, your CR would still be `Tomcat`, your controller class would still be called `TomcatController`, however the default controller name would become `tomcat` instead of `tomcatcontroller` as it is now.

**Comment by adam-sandor** [comment]
Ah ok.. that's fine. Tbh I don't even know where we use controller names in configuration

**Comment by metacosm** [comment]
> Ah ok.. that's fine. Tbh I don't even know where we use controller names in configuration

We don't really at the moment… 😄

**Comment by psycho-ir** [comment]
To me, the controller name itself is more natural than doing any change by convention. And given that a custom resource can have more than a controller I don't think it can be replaced by the resource name.

**Comment by metacosm** [comment]
> and given that a custom resource can have more than a controller I don't think it can be replaced by the resource name.

More complex use cases might indeed run into that issue. Closing this then. Thanks for the input!
