### ISSUE TITLE
Unify logging on operations

### ISSUE THREAD

**Issue by metacosm** [java-operator-sdk/java-operator-sdk#316]
Some operations log information using the UID, others with the CR name. Name is probably better to use for a human than a UID to figure out which CR is having an issue.

**Comment by being-vishal** [comment]
Hello, Greetings..! As it is a good first issue I would like to try out my hands on this issue. Can you help me in getting started?

**Comment by teszes** [comment]
By name, do you mean the string representation of the CR, so this:
`"CustomResource{kind='" + this.getKind() + '\'' + ", apiVersion='" + this.getApiVersion() + '\'' + ", metadata=" + this.metadata + ", spec=" + this.spec + ", status=" + this.status + '}'`

**Comment by teszes** [comment]
Or is it `.getMetadata().getName()`?

**Comment by teszes** [comment]
Also, there are helper methods in `KubernetesResourceUtils.java`, which simplify `resource.getMetadata().getProperty()` calls into `getProperty(resource)`. This is done for version and UID right now, I propose we extend it to other metadata properties for consistency.

**Comment by metacosm** [comment]
- I was thinking about the CR name as defined by `metadata.name` which is the human-readable name for the CR
- Regarding utility methods, I don't think there's a need for that, it's just that some properties are accessed more often than others which might justify a wrapper (but I'm not even convinced that this is that useful either).
