### ISSUE TITLE
v1.6.3 not released to artifactory

### ISSUE THREAD

**Issue by Mallington** [java-operator-sdk/java-operator-sdk#322]
The version 1.6.3 of both the operator-framework-spring-boot-starter and operator-framework does not appear to be present in the artifactory.

![Screenshot 2021-01-25 at 19 20 40](https://user-images.githubusercontent.com/25605615/105755117-c6a34080-5f42-11eb-866b-617fbe3ef6eb.png)
![Screenshot 2021-01-25 at 19 19 42](https://user-images.githubusercontent.com/25605615/105755120-c73bd700-5f42-11eb-88aa-77ae4f3e7e23.png)

**Comment by metacosm** [comment]
Closing this as we recommend to use a more recent version. Please re-open if this is still an issue for you.
