### ISSUE TITLE
Implement DeploymentEventSources in samples using SharedInformers

### ISSUE THREAD

**Issue by adam-sandor** [java-operator-sdk/java-operator-sdk#325]
Currently the DeploymentEventSource in the Tomcat and Memcached samples is implemented using a Watch. Fabric8 now supports [SharedInformers ](https://rohaan.medium.com/introduction-to-fabric8-kubernetes-java-client-informer-api-b945082d69af) which have a nicer API and cache the requested objects. To properly utilize this caching the DeploymentEventSources should be extended with a `get` method which would be used by the Controller to fetch resources from the cache. I think the SharedInformer itself shouldn't be exposed to the Controller but maybe that's not a bad idea either.

**Comment by csviri** [comment]
this is done, see: #659
