### ISSUE TITLE
Generate Deployment, ServiceAccount, RoleBinding for operetor

### ISSUE THREAD

**Issue by adam-sandor** [java-operator-sdk/java-operator-sdk#326]
Deploying an Operator involves creating quite a few Kubernetes objects. We need the Deployment itself for running the Operator, but also a ServiceAccount, Role and RoleBinding. Let's find a way to conveniently generate these for the user additionally to the CRD yaml.

Ideas:
* Use templating
* Use https://github.com/dekorateio/dekorate

**Comment by jmrodri** [comment]
Quarkus extensions will generate this. If we want it for spring boot or others we can revisit.
