### ISSUE TITLE
[BUG] Deleting a secondary resource raises the createOrUpdateResource handler to be called in the controller

### ISSUE THREAD

**Issue by ppatierno** [java-operator-sdk/java-operator-sdk#336]
The scenario is about handling "manual" deletion of secondary resources created by a controller, where by "manual" I mean that after the controller creates a secondary resource, that is deleted by someone else (application or user) interacting with the Kubernetes server API (An example could be the Tomcat controller that creates a `Deployment` as a secondary resource).

In order to watch events for a secondary resource, the way is to extend the `AbstractEventSource` class and implement the `Watcher<T>` interface (to use a watcher) or `ResourceEventHandler<T>` interface (to use an informer). The Tomcat example has `DeploymentEventSource` as a reference.

If "someone" deletes the secondary resource (let's say the created `Deployment`) we would love to have the `deleteResource` handler be called in the controller implementation (so that we can check the `Context` instance to see from where the event is coming) while the problem is that the `createOrUpdateResource` handler is called instead.
What I noticed is that the `EventDispatcher.handleDispatch` doesn't have any logic to handle a delete action coming from a secondary resource (so from an event source) and not from the primary one.

**Comment by csviri** [comment]
@ppatierno this is intentional as explained on Discord. Will explain it more in detail.
