### ISSUE TITLE
crd-generator: option to set where CRDs should be generated

### ISSUE THREAD

**Issue by lburgazzoli** [java-operator-sdk/java-operator-sdk#363]
By default the crd-generator generates the yaml files in `target/classes/META-INF/fabric8` but it would be nice to have an option to specify where they should be generated so as example, one can check in the CRDs to the repository

**Comment by metacosm** [comment]
See https://github.com/fabric8io/kubernetes-client/issues/2842

**Comment by metacosm** [comment]
Where would you like to generate the CRDs for example? Note that the current implementation relies on annotation processing which restricts where the files can be generated…

**Comment by lburgazzoli** [comment]
something like: `src/generated/resources/META-INF/fabric8`

**Comment by metacosm** [comment]
We currently cannot generate in `src` but we could generate them in `target/generated-sources/annotations`. This is due to annotation processing restrictions. We plan on addressing this at some point but this is not a priority at the moment. See fabric8io/kubernetes-client#2836 for more details.

**Comment by lburgazzoli** [comment]
understood however it would be very beneficial IMHO so you can apply a CRD from github directly, no need to build the operator just to get the CRD

**Comment by metacosm** [comment]
Agreed but then, you can also generate the CRD and then commit them… This could probably be implemented as part of the build process…

**Comment by metacosm** [comment]
There's a PR opened for this in the Quarkus extension: https://github.com/quarkiverse/quarkus-operator-sdk/pull/8. This requires the soon-to-be-released 5.2 version of the fabric8 client.

**Comment by metacosm** [comment]
@lburgazzoli the CRD generation process doesn't really allow much flexibility in the way of where the files can be generated, unfortunately. The quarkus extension offers **some** flexibility but still is limited to outputting generated code in `target`. Closing this as won't fix, unfortunately, but more like can't fix… :(
