### ISSUE TITLE
[resource controller] add an option to re-schedule a request

### ISSUE THREAD

**Issue by lburgazzoli** [java-operator-sdk/java-operator-sdk#369]
The method `UpdateControl<R> createOrUpdateResource(R resources, Context<R> context);` has no option to reschedule a request. Usually you should rely on event source but sometimes it is much more simpler to reschedule a reuqest (which is possible in the golang based sdk).

Something like:    

    UpdateControl.reschedule(delay)

Would IMHO, be useful

**Comment by lburgazzoli** [comment]
To expand a little bit more: as part of the reconcile logic of my operator, I need to perform some interaction with an external HTTP service which of course can fail for a number of reasons so as today, the option I have to retry are:

1. throw an exception which would work but it does not give control about when the next reconcile will happen and you may want to implement some logic like back-off 
2. extract the TimerEventSource from the context and and use one of the related schedule method, which would work but looking at the code, it's availability depends on the EventSourceManager implementation (i.e. the default one, has an option to turn on/off the registration of the timer task)
3. register my own TimerEventSource in the EventSourceManager.

Option 3 seems to be the safest one in my case but still wonder if such shenario should be supported out of the box.

**Comment by wtrocki** [comment]
A good example would be operators interacting with API. We need to be able to reschedule requests. 

Scheduler API provides this capability but that is global - we can check things at some time period. 

@lburgazzoli 
The workaround for now is to edit some made-up field in the metadata - then the operator will pick that as event and reschedule.

**Comment by cortex93** [comment]
Periodic reconciliation seems to be a very common use case, that it shouldn't be a big overhead to have the controller base class register it's own TimerEventSource.
I'm using Option 3 without trouble but being closer to the golang SDK would benefit to the whole ecosystem.

**Comment by cortex93** [comment]
@csviri should this be closed by #570

**Comment by csviri** [comment]
yes, will close this.
