### ISSUE TITLE
UpdateControl.updateStatusSubResource(resource) is not updating status

### ISSUE THREAD

**Issue by wtrocki** [java-operator-sdk/java-operator-sdk#371]
Hi

I have this really strange behavior in my operator:
Updates for status subresource stopped working

**Comment by wtrocki** [comment]
Upon investigation I'm pretty sure that this is something to do with the operator itself.

```
UpdateControl.updateStatusSubResource(resource);
```
is called but resource is never updated

**Comment by lburgazzoli** [comment]
So I have a very simple control loop:

```java
@Override
public UpdateControl<MyResource> createOrUpdateResource(
        MyResource resource,
        Context<MyResource> context) {

    if (!resource.getStatus().isInPhase(MyResourceStatus.PhaseType.Ready)) {
        resource.getStatus().setPhase(MyResourceStatus.PhaseType.Ready);
        return UpdateControl.updateStatusSubResource(resource);
    }

    return UpdateControl.noUpdate();
}
```

And I'm observing the same issue as @wtrocki

**Comment by wtrocki** [comment]
Updated to 1.8.0 - seeing the same problem

**Comment by metacosm** [comment]
> Updated to 1.8.0 - seeing the same problem

Which version did you upgrade from, @wtrocki?

**Comment by wtrocki** [comment]
We upgraded everytime version was released. I think bug started to appear in 1.7.2 (not 100% sure)

**Comment by wtrocki** [comment]
Problem autoresolved itself after setting up dependencies again for kubernetes client etc.

**Comment by metacosm** [comment]
Yep, was going to say that I couldn't reproduce it on my side… glad to hear it's solved.
