### ISSUE TITLE
[resource-controller] rename createOrUpdateResource ?

### ISSUE THREAD

**Issue by lburgazzoli** [java-operator-sdk/java-operator-sdk#374]
`ResourceController`'s main entry point is `createOrUpdateResource(R resource, Context<R> context)` seems misleading as in fact the method operates on an already existing CR so not sure if `create` is actually an option.

Maybe `reconcile`  would be a better name ?

**Comment by csviri** [comment]
@lburgazzoli I agree, reaised this actually too. The original idea was that we create or update resources managed by the controller so it's meant like that  (not creating or updating the CR). Or in event context handle createOrUpdate even of a custom resource. However we are currently also support different events from differnet events sources, so this naming does not fit at all IMHO. So the correct name should be `reconcile`.

In addition to that also the `delete` method should be rather `cleanup`.

**Comment by csviri** [comment]
Created a separate issues where described the current changes, please take a look, we can continue the discussion there:
#655

will close this issues for now.
