### ISSUE TITLE
Java Operator from Quarkiverse is not working

### ISSUE THREAD

**Issue by wtrocki** [java-operator-sdk/java-operator-sdk#375]
Could not resolve dependencies for project com.operator:jar:1.0.0-SNAPSHOT: Could not find artifact io.javaoperatorsdk:operator-framework-quarkus-extension:jar:1.8.0.CR1 in central (https://repo.maven.apache.org/maven2) 

It is not there (it might take time to populate)
https://repo.maven.apache.org/maven2/io/javaoperatorsdk/operator-framework-quarkus-extension/

I followed official docs

**Comment by metacosm** [comment]
https://github.com/java-operator-sdk/java-operator-sdk#quarkus
The extension is now found at: https://repo.maven.apache.org/maven2/io/quarkiverse/operatorsdk/quarkus-operator-sdk/
