### ISSUE TITLE
Updating CR spec is not triggering update in SDK

### ISSUE THREAD

**Issue by wtrocki** [java-operator-sdk/java-operator-sdk#376]
Making update in the CR Is not triggering update method in the operator. 
Can be replicated on the sample application

**Comment by wtrocki** [comment]
I'm about to close it. I ended up with this issue because I wanted to force the operator to reschedule my change - but updates in metadata are not triggering changes. Only updates in the spec.

If that is ok we can close this issue

**Comment by metacosm** [comment]
Closing for now.

**Comment by bearpaws** [comment]
@metacosm - I too noticed that reconciliation is not triggered when CR metadata changes (specifically labels and annotations).  Is this intentional and what was the reasoning?

**Comment by csviri** [comment]
@bearpaws yes, this is the feature, described here:
https://javaoperatorsdk.io/docs/features#generation-awareness-and-event-filtering
pls let us know if it is not clear from docs

**Comment by csviri** [comment]
Well, no other, but for example, if you update the status (what you do at the end of reconciliation usually) - so introducing any change to status to be more precise , will trigger a new reconciliation every time. What is not desired usually. So it is better to keep this on if its possible.
