### ISSUE TITLE
Intermittent test failures

### ISSUE THREAD

**Issue by adam-sandor** [java-operator-sdk/java-operator-sdk#379]
This test fails from time to time, not clear why: https://github.com/java-operator-sdk/java-operator-sdk/runs/2131801927?check_suite_focus=true

**Comment by asmacdo** [comment]
Next time this happens could you take a screenshot or copy the info? These logs expire after a while, it would be nice to see them here.

**Comment by jmrodri** [comment]
Closing for now, if new tests fail, please open a new issue with the logs and error message.
