### ISSUE TITLE
Optimize Event Processing on Restart with resourceRersion Aware Way

### ISSUE THREAD

**Issue by csviri** [java-operator-sdk/java-operator-sdk#38]
Currently on startup we process again all the custom resources we are watching. This is not very efficient in case there are huge number of custom resources.

We can have processed just the new events not all of them from a certain resource version. Question is where and when to store the state that what was the last resource version we processed.
( https://kubernetes.io/docs/reference/using-api/api-concepts/#efficient-detection-of-changes )

**Comment by csviri** [comment]
Note that here is quite hard to achieve 100% correctness, because of concurrency issues involved.
If we receive multiple events for at once, its not guaranteed anywhere that in java threading we will start processing them in order according to resource version. So it might happen that operator starts processes a custom resource with a more up to date resource version, while an other thread is blocked with on older resource. If the process at this point fails, we have a lost event on restart.

**Comment by metacosm** [comment]
Closing this for now, will reopen if needed.
