### ISSUE TITLE
Reconciliation: failed retry notification

### ISSUE THREAD

**Issue by csviri** [java-operator-sdk/java-operator-sdk#39]

**Comment by mycrEEpy** [comment]
0.3.9 currently has this issue right? Any updates on when a new version of the merged fix will get a release?

**Comment by csviri** [comment]
Hi, this is a feature, that just currently on level of discussion.
(Will make better descriptions for issues) And its just about how to better notify (other than logs), but have also in case some metrics on failed execution. The retries for fails itself are already merged. 

We plan some changes in the the close future, but we hope we can release a version 1.0.0 at most in february.
