### ISSUE TITLE
No comprehensive Javadoc coverage

### ISSUE THREAD

**Issue by teszes** [java-operator-sdk/java-operator-sdk#431]
Javadoc is used to document some areas of the code, extending this coverage to the entirety of the project would ease both reasoning about the code and the learning curve for new contributors.

**Comment by teszes** [comment]
As discussed at the weekly meeting, Javadoc should be expanded to the io.javaoperatorsdk.operator.api package, but no other packages. Am I correct in this?

I'm adjusting my PR accordingly.

**Comment by jmrodri** [comment]
It seems that what needs discussion here is whether we want to javadoc EVERYTHING including internal classes that are not meant to be a public API. It seems like what definitely needs to be there is javadoc for the public API that users will be interacting with. So I think one of the issues is "what does comprehensive" mean in this context.

**Comment by csviri** [comment]
As far as I remember we agreed that we will have javadoc for the public APIs (which we already have). And document the non obvious behavior / APIs for internals. Will close this issue for now.
