### ISSUE TITLE
Add x-kubernetes-preserve-unknown-field to a CRD

### ISSUE THREAD

**Issue by lburgazzoli** [java-operator-sdk/java-operator-sdk#458]
I have a CRD where I need to include some unspecified fields, and I come up with something like:

```java
class MySpec {
    String foo;
    Map<String, JsonNode> additionalProperties;
    
    @JsonProperty
    public void setFoo(String foo) {...}
    @JsonProperty
    public void getFoo() {...}
          
    @JsonAnySetter
    public void setAdditionalProperty(String key, JsonNode value) {...}

    @JsonAnyGetter
    public Map<String, JsonNode> getAdditionalProperties() {...}
}
```

However, as the generated CRD yaml, does not specify `x-kubernetes-preserve-unknown-field`, all unspecified fields are pruned so i.e. when I'm dogin `kubectl get myresource`, the only field that it is shown is `foo`.

Is there a way to declare that `x-kubernetes-preserve-unknown-field` should be set ?

**Comment by metacosm** [comment]
Not at this point. One thing to note, though, `additionalProperties` is supposed to be mutually exclusive with the `properties` field in the CRD JSONSchema so I'm not sure how that would work out. I've created a fabric8 client ticket, which is where this would be dealt with.

**Comment by andreaTP** [comment]
This feature have been actually implemented in the `kubernetes-client`:

https://github.com/fabric8io/kubernetes-client/pull/3684
https://github.com/fabric8io/kubernetes-client/pull/3691

**Comment by andreaTP** [comment]
This issue is fixed since everything got merged in `kubernetes-client` and JOSDK updated it.

**Comment by metacosm** [comment]
Thanks for confirming, @andreaTP!
