### ISSUE TITLE
Create architecture document

### ISSUE THREAD

**Issue by asmacdo** [java-operator-sdk/java-operator-sdk#482]
Add documentation for how the various projects involved with java operators fit together. For initial implementation, this could just start in the "getting started" guide and be moved into its own section over time.

- fabric
- java-operator-sdk
- java-operator-plugins
- quarkus

**Comment by theishshah** [comment]
@csviri

**Comment by theishshah** [comment]
@laxmikantbpandhare

**Comment by csviri** [comment]
Created this doc, with the diagram, hope it helps:
https://javaoperatorsdk.io/docs/architecture-and-internals

will close this issue for now.
