### ISSUE TITLE
Clone cutom resources before storing them to the cache

### ISSUE THREAD

**Issue by lburgazzoli** [java-operator-sdk/java-operator-sdk#494]
In CustomResourceEventSource, when an event rleated to a customr resource is handled, then the resource is added to the cache and then the same reference is passed to the reconcile loop: 

https://github.com/java-operator-sdk/java-operator-sdk/blob/aa126e7a47020ea6424df855e9581bd87c32238c/operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/event/internal/CustomResourceEventSource.java#L119

Within this approach, the reconcile loop modified the cache entry directly instead of working on a copy. should the resource be cloned before being persisted to the cache ?

**Comment by attilameszaros-form3** [comment]
@lburgazzoli we just clone it after it's read from the cache, so there reference is not the same in the reconcile loop. 

https://github.com/java-operator-sdk/java-operator-sdk/blob/aa126e7a47020ea6424df855e9581bd87c32238c/operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/CustomResourceCache.java#L67

The complete re-work of caching is on roadmap, just have to find time.

**Comment by lburgazzoli** [comment]
Ah yes, but still, the cached reference is [passed to the event handler](https://github.com/java-operator-sdk/java-operator-sdk/blob/aa126e7a47020ea6424df855e9581bd87c32238c/operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/event/internal/CustomResourceEventSource.java#L119-L131 ) as it is so any modification would still lead to an inconsistency right?

**Comment by csviri** [comment]
Yes, the thinking was that is part of the our code, so we know that we are not modifying it. Never reaches the custom code (thus the controller). We have to however clone when reading from cache because that custom resource might be changed by the controller implementation. I'm not saying though that cloning also there would be a bad idea.
