### ISSUE TITLE
Java code style

### ISSUE THREAD

**Issue by lburgazzoli** [java-operator-sdk/java-operator-sdk#504]
I've tried to switch from `fmt-maven-plugin` to `formatter-maven-plugin` to (see #398) and I have configured the plugin to use the eclipse configuration provided in `contributing/eclipse-google-style.xml` hover when the format is applied, some files have been re-formatted, as example:

![image](https://user-images.githubusercontent.com/1868933/130196509-103ab744-fed8-425a-970c-5d6aa0b74b16.png)

My understanding is that most of the reformat happen because of how multi line statement are handled which I think is a minor issue but it reveal that the code style file we ship is not exactly the same as the one that the `fmt-maven-plugin` applies.

I think it would be nice to rely on the `contributing/eclipse-google-style.xml` as it would make the formatting consistent regardless of the IDE/tool (i.e. there is an eclipse code style plugin for IDEA I'm using quite extensively on other projects, VS Code Java Extension support the eclipse config).

**Comment by lburgazzoli** [comment]
I have tweaked a little the provided code style and and I opened a draft [PR](https://github.com/java-operator-sdk/java-operator-sdk/pull/505) to show the formatting that has been applied.

I think the new format is reasonable as:
- it mainly affect the javadocs & comments with a reasonable re-format
- the changes to the code are minimal and very reasonable to me

**Comment by metacosm** [comment]
Yes, that's one thing that annoys me with the current set up: the formatting is not consistent across all implementations (IDEs vs mvn plugin) so it doesn't surprise me that there are discrepancies, unfortunately… 😞
