### ISSUE TITLE
disable colors in test logs

### ISSUE THREAD

**Issue by lburgazzoli** [java-operator-sdk/java-operator-sdk#519]
The log4j config is set-up to use color for loggers but it may lead to a very bad experience:

![image](https://user-images.githubusercontent.com/1868933/131305611-931f212e-8d81-4dd5-b3e3-5e7f81a6895b.png)

Should we removed color options from log4j config ?

**Comment by csviri** [comment]
I don't have very strong opinion on this. If it's done right makes the logs readable, but it is also creating issues when reading the logs on a system that not support it. So I'm ok to turning this off.

**Comment by metacosm** [comment]
I noticed recently that some logging was indeed barely readable. The recent change that introduced this configuration should be reverted, in my opinion.

**Comment by lburgazzoli** [comment]
Before I re-based everything on log4j, the colored logging was only for unit tests
for integration tests it was a mess because there were both slf4j-simple and logback as logging engine so the issue was masked a little.
