### ISSUE TITLE
Can't receive any events about the watched CR after running serveral days

### ISSUE THREAD

**Issue by BenchengZhuo** [java-operator-sdk/java-operator-sdk#522]
#### What did you do?

This issue is similar to [kubernetes-client/issues/2323](https://github.com/fabric8io/kubernetes-client/issues/2323). After my operator runing several days, it can't receive any event about the watched CR. At first, I thought my operator was down. So I added a test REST api for the operator. The test api worked fine while the same thing happened again.

#### Environment

**Kubernetes cluster type:**

Azure
`$ Mention java-operator-sdk version from pom.xml file`

1.9.5

`$ java -version`

openjdk version "11.0.6" 2020-01-14 LTS
OpenJDK Runtime Environment Zulu11.37+17-CA (build 11.0.6+10-LTS)
OpenJDK 64-Bit Server VM Zulu11.37+17-CA (build 11.0.6+10-LTS, mixed mode)

`$ kubectl version`

Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.0", GitCommit:"af46c47ce925f4c4ad5cc8d1fca46c7b77d13b38", GitTreeState:"clean", BuildDate:"2020-12-08T17:59:43Z", GoVersion:"go1.15.5", C
ompiler:"gc", Platform:"windows/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.9", GitCommit:"1af681ff123a96cc50f4f6323a83c70a1daf6950", GitTreeState:"clean", BuildDate:"2021-05-25T17:37:16Z", GoVersion:"go1.15.8", C
ompiler:"gc", Platform:"linux/amd64"}

#### Possible Solution

I saw `var w = client.inNamespace(ns).watch(options, this); `at [CustomResourceEventSource.java#L64](https://github.com/java-operator-sdk/java-operator-sdk/blob/4cbd08e4f63864f352fcb3c7753559e41a4e7f53/operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/event/internal/CustomResourceEventSource.java#L64). Like issue [kubernetes-client/issues/2323](https://github.com/fabric8io/kubernetes-client/issues/2323), does this caused by watcher? could we use informer instead of watcher?

**Comment by csviri** [comment]
Hi @BenchengZhuo , thank you for the feedback. Yes the plan is to migrate to informers shortly, that should hopefully solve this problem.

**Comment by csviri** [comment]
V2 should solve this, also there was a fix for v1, will reopen if this happens again.
