### ISSUE TITLE
Reducing object allocations

### ISSUE THREAD

**Issue by lburgazzoli** [java-operator-sdk/java-operator-sdk#537]
While looking at the event handling I noticed that there a number of object allocation that happening, as example:

    new Event -> new ExecutionScope -> new Context(new EventList) 

Looking at the code, it seems to me that the `ExecutionScope` and `Context` are in essence the same same object as they carry the same information so wonder if we should reduce the number of object we allocate by having the event handling generating an object implementing `Context` and skipping the intermediate `ExecutionScope`. Also I wonder if the wrapping of the events in an `EventList` should be dropped as it does only addition is the `getLatestOfType` method which can probably be moved to the `Context` interface or provided as an utility class.

Relates to:
- https://github.com/java-operator-sdk/java-operator-sdk/issues/406

**Comment by csviri** [comment]
@lburgazzoli I also created an issue which is realted to this, pls take a look.
https://github.com/java-operator-sdk/java-operator-sdk/issues/538
