### ISSUE TITLE
Using only one instance of ScheduledExecutorService

### ISSUE THREAD

**Issue by csviri** [java-operator-sdk/java-operator-sdk#540]
Currently we are using `ScheduledThreadPoolExecutor` per controller. It would be better to control threading and related configurations if it would be shared between controllers. So there are no more such services created.

**Comment by csviri** [comment]
see also: https://github.com/java-operator-sdk/java-operator-sdk/issues/533

**Comment by lburgazzoli** [comment]
eventually the executor service can also been injected i.e. it can use the same thread pool as quarkus
