### ISSUE TITLE
Make it easier to override default `ConfigurationService` values

### ISSUE THREAD

**Issue by metacosm** [java-operator-sdk/java-operator-sdk#542]
We should be providing a `ConfigurationServiceOverrider` similar to what we already do for `ControllerConfiguration`.

**Comment by csviri** [comment]
Just a question, is there a partical reason why the configuration isn't an ordinary POJO? 
If I remember it correctly the reason to do it in the current way was related to qarkus. Cannot be the tranlation between the service and POJO done on quarkus side?

**Comment by metacosm** [comment]
Well, there is a POJO: `DefaultConfigurationService` but we don't want to be using that implementation in the Quarkus extension. That implementation actually generates controllers' configuration on the fly from the controller's class annotations if it's not found in the service already and that's not a behavior we want in the Quarkus extension, which is why we have an interface. Spring Boot also uses its own implementation based on `AbstractConfigurationService`.
