### ISSUE TITLE
Do not run tests when releasing a snapshot

### ISSUE THREAD

**Issue by metacosm** [java-operator-sdk/java-operator-sdk#547]
Tests are already run before the release attempt occurs so there's no need to run them again.

**Comment by csviri** [comment]
Does this harm, I usually prefer to run tests as often as possible :)

**Comment by metacosm** [comment]
> Does this harm, I usually prefer to run tests as often as possible :)

The tests are run twice when we release: first as part of the regular PR checking process with the whole matrix, then once again for the actual release build. If the tests passed during the first step, there is no need to run one of them again during the release process. This also can be seen when PR tests work but then the release snapshot fails because of a test flake…

**Comment by csviri** [comment]
Ahh ok, sorry, this is how it meant. Kk sounds good :)

**Comment by MovieMaker93** [comment]
Should I remove the test in the master-snapshot-release.yml?

**Comment by metacosm** [comment]
We could probably remove them there indeed. However that would mean we need to always create PRs instead of committing to master directly as we do once in a while… I was more talking about `release.yml` but I'm actually not sure if we can not run the tests with the `samuelmeuli/action-maven-publish` action.

**Comment by metacosm** [comment]
Fixed by #859
