### ISSUE TITLE
Use Controller name as finalizer

### ISSUE THREAD

**Issue by adam-sandor** [java-operator-sdk/java-operator-sdk#57]
Use the name of the controller as the finalizer string, but keep it customizable.

**Comment by ng29** [comment]
Hey @adam-sandor  / @charlottemach  
Can i work on this ?? 
Some more info around this will be highly appreciated 👍

**Comment by csviri** [comment]
Hi @ng29 welcome!
currently if you check the master we read the finalizer name from the annotation, where is always a default if not set. 
The idea was, that if its not configured expicitly we don't use the default but the [packag+"."+classNameOfController] with lowercase.

**Comment by escher-m** [comment]
I've added some code based on my understanding of the info. Please let me know if this covers what was intended @csviri
