### ISSUE TITLE
Provide a no-dependency `Metrics` class implementation

### ISSUE THREAD

**Issue by metacosm** [java-operator-sdk/java-operator-sdk#576]
We should separate the `Metrics` class from micrometer so that users who are not interested in monitoring don't carry the dependency. This would mean creating a separate module for the micrometer-based implementation.

**Comment by csviri** [comment]
I'm just wondering if this is worth it. I mean what we get when we don't have micrometer core on classpath? 
its around ~600kB, but when we build the app with dependencies its already ~25MB, so it's an overhead in size but not significant. The classes are not loaded by the class loader if they are not used. 

So are you sure if this change has that much added benefit?

**Comment by csviri** [comment]
Also thinking is we could trick this without a new module, if somebody is not using it. So build it with "provided" dependency, but if somebody will jus tset an empty metric class with not dependency on actual micrometer, it could work. Not sure though.
