### ISSUE TITLE
We might want to avoid closing the client when we close the Operator.

### ISSUE THREAD

**Issue by iocanel** [java-operator-sdk/java-operator-sdk#585]
Currently, the `KubernetesClient` instance is passed externally to the `Operator`. I am wondering if its a good idea to close it when we close the `Operator`, given that its created externally and we can't possibly know who else is using it.

For example, in a test one may close the operator and use the client to perform some cleaning up afterwards, which could possilby lead to issues.

I don't have a strong opinion about it, but my experience from the kubernetes-client tells me that each time we took liberty to close objects passed externally, it didn't end up well and that's why I am bringing this up for discussion.

**Comment by csviri** [comment]
Agree, here the principle holds as for example on streams, so it should be closed on the layer where opened.
We could make it more explicit, like have a flag to close it or not. That might be a compromise. (Being aware that we have now a constructor without a client :) )

**Comment by metacosm** [comment]
@csviri should we change this for v2?

**Comment by csviri** [comment]
Yes, we can have it in v2 IMHO

**Comment by csviri** [comment]
Added a flag to be able to avoid this, IMHO this is now the common behavior, how users use it. So the default remains to close the client.
