### ISSUE TITLE
Make samples more standalone

### ISSUE THREAD

**Issue by iocanel** [java-operator-sdk/java-operator-sdk#586]
It would be nice if samples were standalone.

By standalone I mean:
- have documentation directly in the project directory
- able to run outside the context of the project (e.g. remove parent).
- contain internally all resources they require

The reasoning is pretty simple, one should be able to just copy the sample directory and be able to get started, without having to mess with parents etc.

**Comment by metacosm** [comment]
Yes, the samples are really simple ones more meant to be smoke-tests for changes made in the core than real examples.

**Comment by csviri** [comment]
Will close this issue, after this, it should be covered mostly:
https://github.com/java-operator-sdk/java-operator-sdk/issues/590
