### ISSUE TITLE
Caching just Updated Custom Resource Optimization alternatives

### ISSUE THREAD

**Issue by csviri** [java-operator-sdk/java-operator-sdk#588]
In case we execute a controller and update the custom resource at the end, it can take time while we receive the custom resource event from the server and gets into the informers cache in `CustomResoureEventSource` .  This causes problem in case when there are already events received during the execution. In next reconciliation , what happens instantly, we use an old custom resource, and the next update will fail on conflict.

We handled this situation in V1 but simply caching manually the updated custom resource from the response of the update api call. Currently we cannot do this with informers (well not with a very hacky way)

Note that if there is retry in place this is not a correctness issue just an optimization, but this is possibly happening quite often, and it's quite ugly. Since we see lots of retries.

Alternative solutions to V2:
1. Don't execute the buffered events instantly, just schedule a new one time event in the close feature (~1-2 second?), usually we receive the update custom resource until that time into cache (not necessary to the Event Handler because of generation filtering). We have to be careful there this event producing should be cancelled in case the event arrives. (I prefer this)
(This would be also reusable to optimize the re scheduling of events)

2. Don't filter out the next event from custom resource event source. This will allow to receive the event about the update and execute the custom resource. Note that is hard to make correct (if not impossible now) in all cases, there are possible timing issues we have to investiage)

3. the combination of  1. and 2.

**Comment by metacosm** [comment]
Shouldn't event only occur when the informer is updated, though? In which situation would there be events that are not associated to an informer update?

**Comment by metacosm** [comment]
One possible option, though a tricky one to implement would be to delay updating the resource on the server until all the events are processed. Another option would be to have an ephemeral cache of the resource that would only span the current interaction (though I guess defining that interaction might be tricky as well).
