### ISSUE TITLE
Status update triggers reconciliation with finalizers disabled

### ISSUE THREAD

**Issue by shawkins** [java-operator-sdk/java-operator-sdk#595]
## Bug Report

When using ```@Controller(finalizerName = Controller.NO_FINALIZER)``` an update to just the status of the primary resource will itself cause another reconciliation - which is a fairly tight processing loop.  With the finalizer enabled no event loop is seen.

#### What did you expect to see?

The status update will not trigger an immediate reconciliation.

#### What did you see instead? Under which circumstances?

Operator sdk version 1.9.6 via the 2.0.0.Beta5 quarkus extension.

#### Environment

Openshift 4.8

**Comment by shawkins** [comment]
I tried upgrading just the sdk dependency to 1.9.8 and confirmed that things worked as expected.

**Comment by csviri** [comment]
Hi @shawkins , thank you for the report!
The finalizer should not be relevant to this. 
The status update, although its a subresource, updates the custom resource also in sense, that the `resourceVersion` is updated for example. So naturally an event should be received. However to prevent reconciliation we filter on `metadata.generation`, in this case the generation is not increased and (if this not turned explicitly off) the reconciliation should not happen as you mention.

**Comment by shawkins** [comment]
> Do I understand correctly that it work as expected in a more recent version and we can close the issue?

If you are good with the explanation of why it was occurring and what has addressed it, yes it can be closed.
