### ISSUE TITLE
Connectivity to kubernetes API for clusters without valid certificate

### ISSUE THREAD

**Issue by wtrocki** [java-operator-sdk/java-operator-sdk#605]
## Bug Report

Hi

We have been using operator SDK with various test environments some of those do not have valid cert.
When running operator on that environment we get the error:

```
OkHttp https://172.30.0.1/...) Exec Failure: javax.net.ssl.SSLException: 
```

We did not specify ` https://172.30.0.1` anywhere in our operator, but I was wondering why https and not HTTP is being used?
Is there any way for us to prevent this from happening?

I see fabric kubernetes client having configuration options that allow us to override values or prevent from checking certificates but none of those were actually working with Operator SDK (our own Kubernetes client instance picks those but no operator internal calls did)

Is there any solution/recomendation/documentation for this kind of issue?

Ref
https://github.com/redhat-developer/app-services-operator/issues/269

**Comment by jmrodri** [comment]
@wtrocki do you have a complete stacktrace  of the error?
