### ISSUE TITLE
Question & Opinion) ResourceController's init(EventSourceManager) method feels a bit vague.

### ISSUE THREAD

**Issue by heesuk-ahn** [java-operator-sdk/java-operator-sdk#615]
HI, all
I was wondering how to register eventSource in Controller, so I looked at the code.

https://github.com/java-operator-sdk/java-operator-sdk/blob/2e8f219437e53b9ca58f146a24397dbf38f0bfb8/operator-framework-core/src/main/java/io/javaoperatorsdk/operator/api/ResourceController.java#L55

Looking at this method, it looks like I can create and use my own `EventSourceManager`.

However, in reality, when `operator.start()` starts, `DefaultEventSourceManager` is unconditionally injected in `configuredController.`
(https://github.com/java-operator-sdk/java-operator-sdk/blob/2e8f219437e53b9ca58f146a24397dbf38f0bfb8/operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/ConfiguredController.java#L178-L179)

And actually, the user should directly register the `EventSource` that the user wants to register with the EventSourceManager inside the init method. 
like this

```
  @Override
  public void init(EventSourceManager eventSourceManager) {
    ...
    eventSourceManager.registerEventSource(eventSource);
  }
```

Personally, I think this might be a bit ambiguous.
It feels like the user can directly inject and use CustomEventSourceManager .

If that's not what you intended, Rather, I think the interface below would be a little clearer.

```
public interface ResourceController<R extends CustomResource> {
 ...
  default List<EventSource> registerEventSources() {
    return List.of();
  }
}
```

And by calling this method in the framework, it will be able to directly register it with the event source manager.

Since `EventSourceManager` is an important component in the framework, it seems to be able to prevent it from being directly exposed to users.

This is just my personal opinion.
Thank you for reading this question :)

**Comment by metacosm** [comment]
We could indeed rename `ResourceController` to `Reconciler` to be more in line with `controller-runtime` but I think that renaming `DefaultEventHandler` to `Controller` would be confusing because the `EventHandler` doesn't really match well with what the a golang `Controller` is doing.

**Comment by heesuk-ahn** [comment]
@metacosm

I agree with your opinion. In my opinion, Controller is a higher level concept than EventHandler.

**Comment by csviri** [comment]
Well, if you take a look on the implementation it is not far either:
https://github.com/kubernetes-sigs/controller-runtime/blob/master/pkg/internal/controller/controller.go

- Basically manages the queues - in our case it's basically the executor.
- It calls the Reconciler, what we do too, just adding an additional layer by the dispatcher to implement some higher level logic. 
- Reconcile handler (https://github.com/kubernetes-sigs/controller-runtime/blob/c73b143dc50358328b9153329b3b570b1a0e5623/pkg/internal/controller/controller.go#L287) also does the same / similar logic that we do after reconcile with re-scheduling (and exception handling)

It's different that in our case the DefaultEventHandler does not owns/manages the watch. I think this makes sense actually to separate.

So actually this looks quite close to me.

**Comment by metacosm** [comment]
Ultimately, it doesn't matter, indeed since `DefaultEventHandler` is an internal class. Renaming `ResourceController` makes sense, the rest, not so much.

**Comment by csviri** [comment]
Started to working on this, two related questions:

1. Should we rename the `createOrUpdateResource` to `reconcile`, and `deleteResource` to `cleanup` ? (see linked issues). For now renamed the to plural ( to `createOrUpdateResources`), because in the current way it feels like we are creating the custom resource itslef.

2. We have also a `@Controller` annotation, which actually contains more controller related configurations, not just the reconciler. Just feels weird putting this annotation to reconciler class. Would it be an idea to rename it to `@ControllerConfiguration`?

**Comment by lburgazzoli** [comment]
> Ultimately, it doesn't matter, indeed since `DefaultEventHandler` is an internal class. Renaming `ResourceController` makes sense, the rest, not so much.

hijacking a little the discussion but here we could think to rename it to `DefaultEventHandler` to `EventHandler` as it does not seems to me we support pluggable `EventHandler` (I think there are other cases where we have an interface whit a single and not user customizable interface).

**Comment by csviri** [comment]
> hijacking a little the discussion but here we could think to rename it to DefaultEventHandler to EventHandler as it does not seems to me we support pluggable EventHandler (I think there are other cases where we have an interface whit a single and not user customizable interface).

Will do it, just we have an `EventHandler` interface, and here the purpose with that is not to have a replaceable implementation but to provide an interface to the users to work with. This is used in the  EventSources, so if somebody propagates the event it does it agains the `EventHandler` interface not to the class, which has other public methods.

So we have to find a good naming to DefaultEventHandler, maybe `EventProcessor` ?

**Comment by csviri** [comment]
For now renamed `DefaultEventHandler` to `EventProcessor`.

**Comment by csviri** [comment]
Back to the original topic. We have to bear in mind that the EventSources needs to accessible from the (now) Reconciler, since the caching states of the related reasources are happening in the EventSources. 

Given this constraints it's hard to separate these two completely, not even if we have a completely separate caching layer under the hood of the kubernetes client, since there can be non K8S dependent resources.

**Comment by csviri** [comment]
Created a separate issues where described the current changes, please take a look, we can continue the discussion there:
https://github.com/java-operator-sdk/java-operator-sdk/issues/655

will close this issues for now.
