### ISSUE TITLE
[Refactoring Suggestions] refactored Operator.register api in v2

### ISSUE THREAD

**Issue by heesuk-ahn** [java-operator-sdk/java-operator-sdk#687]
## Motivation

Operator register api of v2 can remove the part that passes `null` as a parameter through method overloading.

In this case, we can remove the logic to protect null from the logic inside the register api.

This can make register api code more readable.

## Proposal

* Change deprecated `kubernetesClient.getVersion` to `KubernetesClient.getKubernetesVersion`
* Pass a non-null value as a parameter by creating `defaultConfiguration` in register(Reconciler<R> reconciler)
* Remove unnecessary null defense code

**Comment by heesuk-ahn** [comment]
I created a pull request to show an example. :) 

https://github.com/java-operator-sdk/java-operator-sdk/pull/688

**Comment by csviri** [comment]
Makes sense to me , also PR looks good. Thank you!
