### ISSUE TITLE
Switch main branch from master to main

### ISSUE THREAD

**Issue by adam-sandor** [java-operator-sdk/java-operator-sdk#690]
I'd say V2 is the perfect time to switch to using main branch instead of master.

**Comment by csviri** [comment]
yes, agree. For late this week the M1 is planned to be released, will do the switch that time if not objections.

Also @metacosm is working on fixes for quarkus extension AFAIK, do you tink we will need a release for the SDK itself for that?

**Comment by metacosm** [comment]
Yes, we probably should release a version of 1.9.x as well.

**Comment by csviri** [comment]
Accidentally released 1.10.0, I mean to test it  but turns out the workflow is picked up from the branch where the tag is selected from. [facepalm]
But renamed master to main. Now main is the default branch.

**Comment by metacosm** [comment]
Not sure if we can get `1.10.0` removed from Maven central…

**Comment by metacosm** [comment]
Then again, the release is there so… 🤷🏼 
This issue should be closed now, though, correct?

**Comment by csviri** [comment]
> Not sure if we can get `1.10.0` removed from Maven central…

Me neither. Maybe @adam-sandor ?

Sure will close the issue.
