### ISSUE TITLE
Can the default eventsource `ControllerResourceEventSource` in operator v2 be improved to use `resync` of informer?

### ISSUE THREAD

**Issue by heesuk-ahn** [java-operator-sdk/java-operator-sdk#727]
### Motivation
***

`ControllerResourceEventSource` is the default eventsource and is created together when `EventSourceManager` is created.

ControllerResourceEventSource watches a specific Resource Type through Informer API.

Let's assume the Resource Type is `kind: Tomcat`.

If `Tomcat Resource` is created as follows, `ControllerResourceEventSource` receives this event and passes it to `EventProcessor` to process the event.

**[tomcat-sample1.yaml]**

```yaml
apiVersion: "tomcatoperator.io/v1"
kind: Tomcat
metadata:
  name: test-tomcat1
spec:
  version: 9.0
  replicas: 2
```

**[ControllerResourceEventSource Event Processing]**

![스크린샷 2021-12-01 오후 3 58 04](https://user-images.githubusercontent.com/42938941/144193376-b7179ae9-0f05-40c8-be78-19dc9cb80cd1.png)

so, If we go through the above process, we can see that Deployment and Service , which are dependent resources of `Tomcat` resource, have been created as shown below.

```bash
## tomcat resource
$ kubectl get tomcat
NAME           AGE
test-tomcat1   44m
```

```bash
## service resoruce (dependenct resoruce by tomcat)
$ kubectl get svc
NAME           TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)        AGE
test-tomcat1   NodePort    10.101.161.213   <none>        80:30557/TCP   5s
```

```bash
## deployment resource (dependenct resource by tomcat)
$ kubectl get deployments
NAME           READY   UP-TO-DATE   AVAILABLE   AGE
test-tomcat1   2/2     2            2           39m
```

```bash
## pod resource (dependenct resource by deployment)
$ kubectl get pods
NAME                            READY   STATUS    RESTARTS   AGE
test-tomcat1-68c49b8b68-4l4hs   2/2     Running   0          39m
test-tomcat1-68c49b8b68-mb5tx   2/2     Running   0          39m
```

Up to this point, the Operator has created the desired Desired State and Acutal State using Reconcile. This is very good.

But what if the Dependent Resource `Deployment` or `Service` is deleted by someone or due to a sudden failure or redeployment?

If the EventSource for Dependent Resource is not specified, reconciliation does not work and the desired state and actual state will be broken.

Now let's actually delete `Deployment`.

```bash
$ kubectl delete deployments/test-tomcat1
deployment.apps "test-tomcat1" deleted
```

```bash
$ kubectl get pods
NAME                            READY   STATUS        RESTARTS   AGE
test-tomcat1-68c49b8b68-4l4hs   2/2     Terminating   0          46m
test-tomcat1-68c49b8b68-mb5tx   2/2     Terminating   0          46m
```

As the Deployment is deleted, the Pods are also deleted accordingly.

In order to satisfy the desired state of the `Tomcat` resource, `Deployments`, a dependent resource, must be revived.

But unfortunately it doesn't come back to life. This is the same even if the Service is deleted.

In this situation we can see that `Desired State != Actual State`.

To ensure this, it may cost development to create EventSource for each Dependency Resource.

### Idea - Use Informer's Resync
***

Another way to guarantee this without creating a dependent event source is to use informer's `resync`.

![스크린샷 2021-12-01 오후 3 40 57](https://user-images.githubusercontent.com/42938941/144193809-ebe34cc0-c75d-4d73-b871-59634860ba24.png) (source. the programming kubernetes book)

The informer api uses the `resync period` to retrieve the latest resources from the cache store and triggers the `UPDATE` event at regular intervals to execute.

If you look at the code below, you can see that informer's scheduler triggers an UPDATE event at intervals of `resyncPeriod`.

[`DefaultSharedIndexInformer - scheduleResync`](https://github.com/fabric8io/kubernetes-client/blob/ef19182a67661a26c13479f58d153ddff3120738/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/informers/impl/DefaultSharedIndexInformer.java#L206-L214
)

[`ProcessStore - resync`](https://github.com/fabric8io/kubernetes-client/blob/8c67e5821ae53fb28640390c8fd9ebb0196558d0/kubernetes-client/src/main/java/io/fabric8/kubernetes/client/informers/cache/ProcessorStore.java#L97-L100)

When the function is used, an UPDATE event is generated for the latest resoruce for each resync cycle, reconciliation is re-triggered, and desired state == actual state can be adjusted.

https://github.com/java-operator-sdk/java-operator-sdk/blob/80ff2449ced3f6cb3db83cf121552e6b867a5960/operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/event/source/ControllerResourceEventSource.java#L109

Currently, `runnableInformer(0)` is set to zero in the code above, so re-sync is disabled.

What if we could put the re-sync property we want here?

```java
// just hard cording for example..
var reSyncPeriod = 5000;
var informer = filteredBySelectorClient.runnableInformer(reSyncPeriod);
```

https://github.com/java-operator-sdk/java-operator-sdk/blob/80ff2449ced3f6cb3db83cf121552e6b867a5960/operator-framework-core/src/main/java/io/javaoperatorsdk/operator/processing/event/source/ControllerResourceEventSource.java#L128-L145

```
// example : In case of update event, it is processed to be event triggered
// In the case of update in filter, it can be refactored to pass.
if (action.name().equals(ResourceAction.UPDATED.name())
   || filter.acceptChange(controller.getConfiguration(), oldResource, customResource)) {
....
```

If Re-Sync is activated as above, the Re-sync event is triggered at regular intervals. Let's look at the log.

```
05:05:49.524 DEBUG io.fabric8.kubernetes.client.informers.ResyncRunnable.run(ResyncRunnable.java:42) - ResyncRunnable#resync .. ..
05:05:49.525 DEBUG io.fabric8.kubernetes.client.informers.ResyncRunnable.run(ResyncRunnable.java:47) - ResyncRunnable#force resync
05:05:49.525 DEBUG io.javaoperatorsdk.operator.processing.event.source.ControllerResourceEventSource.eventReceived(ControllerResourceEventSource.java:145) - Event received for resource: test-tomcat1
```

If you look at the log above, you can see that ReSync is running.

Now, what will happen if you delete Deployment or Service again as above?

```
$ kubectl delete deployments/test-tomcat1
deployment.apps "test-tomcat1" deleted
```

```
$ kubectl get pods
NAME                            READY   STATUS        RESTARTS   AGE
test-tomcat1-68c49b8b68-4l4hs   2/2     Terminating   0          46m
test-tomcat1-68c49b8b68-mb5tx   2/2     Terminating   0          46m
```

It goes down as above, but when the re-sync cycle returns, reconcile is performed again to match the desired state.

```
$ kubectl get pods
NAME                            READY   STATUS              RESTARTS   AGE
test-tomcat1-68c49b8b68-4l4hs   2/2     Terminating         0          46m
test-tomcat1-68c49b8b68-6h8vt   0/2     ContainerCreating   0          0s
test-tomcat1-68c49b8b68-mb5tx   2/2     Terminating         0          46m
test-tomcat1-68c49b8b68-qm57f   0/2     ContainerCreating   0          0s
```

If you really want to delete these, you should delete the `Tomcat` resource with `DesiredState`.

```
$ kubectl delete tomcat/test-tomcat1
tomcat.tomcatoperator.io "test-tomcat1" deleted
```

## proposal

* Improve the execution of resync by passing the resync period parameter to the `ControllerResourceEventSource` (default event source)

**Comment by csviri** [comment]
Hi @heesuk-ahn , not sure if following but how this is different functionally speaking from invoking `UpdateControl.rescheduleAfter(time)`?

**Comment by lburgazzoli** [comment]
> 
> To ensure this, it may cost development to create EventSource for each Dependency Resource.
> ### Idea - Use Informer's Resync
> 
> Another way to guarantee this without creating a dependent event source is to use informer's `resync`.
> 

This need to be used with care as my understanding is that it would re-trigger the reconcile for all the resources which may be very costly if you have a large number of resources to deal with as opposite to re-trigger the reconcile only for those that have effectively been modified outside the reconcile loop.

That's said, I think this is possible but need to be carefully take into account.

> ```
> // example : In case of update event, it is processed to be event triggered
> // In the case of update in filter, it can be refactored to pass.
> if (action.name().equals(ResourceAction.UPDATED.name())
>    || filter.acceptChange(controller.getConfiguration(), oldResource, customResource)) {
> ....
> ```

This may be problematic as one of the reason the filter has been introduced is exactly to filter out spurious updates so as example, by allowing any UPDATE to be propagated, then you are probably also skipping the filter about `generation` vs `observedGeneration` (it's been a wile since I looked at the code but I recall the re was something related to this)

**Comment by heesuk-ahn** [comment]
> Hi @heesuk-ahn , not sure if following but how this is different functionally speaking from invoking `UpdateControl.rescheduleAfter(time)`?

II don't know about `UpdateControl.rescheduleAfter(time)` API. :) 
If I use this, is it used to re-trigger the latest resource at regular intervals?

**Comment by csviri** [comment]
Yes, exactly, I mean the actual resource.

**Comment by heesuk-ahn** [comment]
> > To ensure this, it may cost development to create EventSource for each Dependency Resource.
> > ### Idea - Use Informer's Resync
> > Another way to guarantee this without creating a dependent event source is to use informer's `resync`.
> 
> This need to be used with care as my understanding is that it would re-trigger the reconcile for all the resources which may be very costly if you have a large number of resources to deal with as opposite to re-trigger the reconcile only for those that have effectively been modified outside the reconcile loop.
> 
> That's said, I think this is possible but need to be carefully take into account.
> 
> > ```
> > // example : In case of update event, it is processed to be event triggered
> > // In the case of update in filter, it can be refactored to pass.
> > if (action.name().equals(ResourceAction.UPDATED.name())
> >    || filter.acceptChange(controller.getConfiguration(), oldResource, customResource)) {
> > ....
> > ```
> 
> This may be problematic as one of the reason the filter has been introduced is exactly to filter out spurious updates so as example, by allowing any UPDATE to be propagated, then you are probably also skipping the filter about `generation` vs `observedGeneration` (it's been a wile since I looked at the code but I recall the re was something related to this)

I agree with your opinion. It seems recommended to set `resync-period` to several minutes. 🤔

**Comment by csviri** [comment]
Well it depends, if you have informers for every dependent resource, it not might be necessary. Since you get triggered if any change happens on dependent managed resources.

**Comment by heesuk-ahn** [comment]
> Well it depends, if you have informers for every dependent resource, it not might be necessary. Since you get triggered if any change happens on dependent managed resources.

You're right. 👍 
I was worried about whether to create an eventResource for dependent resource every time. 🤔

**Comment by lburgazzoli** [comment]
> > Well it depends, if you have informers for every dependent resource, it not might be necessary. Since you get triggered if any change happens on dependent managed resources.
> 
> You're right. +1 I was worried about whether to create an eventResource for dependent resource every time. thinking
> 

Usually I do create an event source per kind with a filter on labels

**Comment by kanedafromparis** [comment]
Therefore I wonder, what do you think of adding a methode
"createRessource(HasMetadata resource)" which will add labels and
ownerReference, and Event to the eventResource created by the operator ?

something like that?

```

resource.getMetadata().getLabels().put("app.kubernetes.io/part-of", ...);
resource.getMetadata().getLabels().put("app.kubernetes.io/managed-by", ...);
resource.getMetadata().getLabels().put("app.kubernetes.io/created-by",
this.class.getCanonicalName());
...
OwnerReference ownerReference =
resource.getMetadata().getOwnerReferences().get(0);
ownerReference.setName(this.getMetadata().getName());
ownerReference.setUid(this.getMetadata().getUid());


```

Do you think this belongs to the framework or to the Operator created with
the framework ?

Le mer. 1 déc. 2021 à 10:57, Luca Burgazzoli ***@***.***> a
écrit :

**Comment by lburgazzoli** [comment]
> Therefore I wonder, what do you think of adding a methode "createRessource(HasMetadata resource)" which will add labels and ownerReference, and Event to the eventResource created by the operator ? 

My feeling is that this is really business specific so I see this to be part of the specific operator codebase rather than generic one

**Comment by csviri** [comment]
I see more this like an utility for label, maybe for recommended label, see: https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/
But agree with @lburgazzoli  others can be quite domain specific.

**Comment by heesuk-ahn** [comment]
Perhaps I should close the issue if there is no other special discussion here. :)

**Comment by csviri** [comment]
Yes, I think we can close it.
