### ISSUE TITLE
How can we de-couple Reconciler and EventInitializer?

### ISSUE THREAD

**Issue by heesuk-ahn** [java-operator-sdk/java-operator-sdk#728]
## Motivation

---

One of the changes in operator v2 is the `EventInitializer` interface.

`EventInitializer` is an interface to create `EventSource` used in `EventSourceManager`.

To create and register EventInitializer, `EventInitializer` must be implemented by inheriting interface from Reconciler.

```java
public class TomcatReconciler implements Reconciler<Tomcat>, EventInitlizer<Tomcat> {

  @Override
  public void prepareEventSources(EventSourceRegistry<Tomcat> eventSourceRegistry) {
    eventSourceRegistry.registerEventSource(...)
  }

  ...

}
```

ReConcilier is a class where the business logic defined by the user is located, and I do not think that registering EventSource using EventInitlizer here is not compatible with the single responsibility principle.

So, I was thinking about making these two parts to be used separately.

## Idea 1-1. Operator takes responsibility for registering Reconciler and EventSource

---

It's a rough idea, but the `reconciler` and `eventsources` are delivered to the operator through the `register api`

```java
public class Operator implements AutoCloseable, LifecycleAware {

.
.
.
  // example - register api with eventSourceInitializers
  public <R extends HasMetadata> void register(
     Reconciler<R> reconciler,
     List<EventSourceInitializer<R>> eventSourceInitializers)
.
.
.
}
```

```java
// example - inject eventsource initiliazers by using register api
final var tomcatReconciler = new TomcatReconciler(client);
final var tomcatEventSource = TomcatEventSourceInitializer.createInstance(client);

operator.register(tomcatReconciler, List.of(tomcatEventSource));
```

Through the above API, `Reconciler` and `EventSources` can be passed as parameters when a Controller is created inside the Operator.

```java
final var controller = new Controller<>(
  reconciler,
  defaultConfiguration,
  kubernetesClient,
  eventSourceInitializers);
```

Then inside the controller we can take the responsibility of registering the event source instead of the reconciler.

```java
public class Controller<R extends HasMetadata> implements Reconciler<R>,
    LifecycleAware, EventSourceInitializer<R> {
.
.
	public void start() throws OperatorException {
          // example - 
         // The controller takes responsibility for registering the eventSource instead of the reconciler
	  eventSourceManager = new EventSourceManager<>(this);
	  eventSourceInitializers.forEach(eventSourceInitializer -> 
	    eventSourceInitializer.prepareEventSources(eventSourceManager));
    
	}
.
.
}
```

### Idea 1-2. Use the Context interface to access the EventSource from the Reconciler

---

We separated the EventSourceInitilizer above, but the problem here is that we may need to access the eventsource from the reconcile .

One of the ways to solve this is to use context for reconcile api. 

```java

public UpdateControl<Tomcat> reconcile(Tomcat tomcat, Context context)
```

Currently, only RetryInfo exists in Context, but it seems to be possible to use Map or other object to query EventSource here.

As a simple example, let's say you use Map.

```java
public interface Context {

  Optional<RetryInfo> getRetryInfo();

  Map<Class<? extends EventSource>, EventSource> getEventSourceMap();

}
```

```java
public UpdateControl<Tomcat> reconcile(Tomcat tomcat, Context context) {
  
    final var controllerResourceEventSource =
        (ControllerResourceEventSource) context.getEventSourceMap().get(ControllerResourceEventSource.class);
    final var resourceCache = controllerResourceEventSource.getResourceCache();

    ...
    return UpdateControl.noUpdate();
}
```

Then we can access the default event sources in the reconcile as well.

Of course, at this point, EventInitializer and Reconciler are separated, so the EventSource we created directly can be used by injecting it as a constructor parameter.

```java
public class TomcatReconciler implements Reconciler<Tomcat> {

  private final KubernetesClient kubernetesClient;
  private final InformerEventSource<Deployment> myInformer;

  public TomcatReconciler(KubernetesClient client,
                          InformerEventSource<Deployment> myInformer) {
    this.kubernetesClient = client;
    this.myInformer = myInformer;
  }

}
```

### IDEA 1-3) All EventSources are created directly by the user

---

Currently, `ControllerResourceEventSource` as the Default EventSource is directly created and used in `EventSourceManager`. If this Default EventSource is also changed to be injected into the Operator by the user, it can be easier to access the Store at the user level without modifying the `Context` interface.

### Purpose

---

- IDEA 1) Decoupling for Reconciler and EventInitializer
- IDEA 1-2) Passing EventSource or Cache Store through Context in framework
- IDEA 1-3) All EventSources are created directly by the user

**Comment by csviri** [comment]
Hi @heesuk-ahn , thx for the issues. I think this should be decoupled, so the idea is good, I'm totally align. 

Some comments:

1.
```
  public <R extends HasMetadata> void register(
     Reconciler<R> reconciler,
     List<EventSourceInitializer<R>> eventSourceInitializers)
```
here it should be one initializer, not a List, where all the initialization happening.

2. regarding the idea `1-2`:
```
 final var controllerResourceEventSource =
        (ControllerResourceEventSource) context.getEventSourceMap().get(ControllerResourceEventSource.class);
    final var resourceCache = controllerResourceEventSource.getResourceCache();
```

this is basically that we wanted to avoid with the current approach, so mostly you always want to have access to these event source in order to access the cache. Getting access to them through the `context` is not that nice IMHO. It would be even better to pass them through the constructor if needed,  since you always need it and need it just in the reconciler not sure if initializing them inside the reconciler makes it more convenient. 

But would like to hear others opinion too. Maybe @lburgazzoli @metacosm .

**Comment by lburgazzoli** [comment]
I'm +1 to what @csviri said and in general to use interfaces as marker as it make it easy to add additional feature in the future without breaking the APIs

**Comment by metacosm** [comment]
Note that this is likely to change with the dependent resources work that I'm working on. See for example: https://github.com/java-operator-sdk/java-operator-sdk/pull/726/files#diff-897a97d4dc7895b7f9f215c27d328be7b024c1267ef07b989af23e3052047bc6R143-R167, the idea here being that people should rarely need to implement `EventSourceInitializer` anymore.

**Comment by heesuk-ahn** [comment]
> this is basically that we wanted to avoid with the current approach, so mostly you always want to have access to these event source in order to access the cache. Getting access to them through the `context` is not that nice IMHO. It would be even better to pass them through the constructor if needed, since you always need it and need it just in the reconciler not sure if initializing them inside the reconciler makes it more convenient. So the current approach is basically a pragmatic compromise because of this.

1. Oh right, EventSourceInitlizer is not a List, and multiple EventSources can be registered in it.  :) 

2. I agree, I think the Cache should not be accessed only from within the Reconcile. IDEA 1-3 seems to be similar. 🤔 

Currently, the Cache of ControllerResourceEventSource is injected inside the framework, so to access it from the Reconciler, it must be accessed through `EventSourceRegistry.getControllerResourceEventSource().getResourceCache()` in `prepareEventSources`.

However, the problem of approaching this way can eventually become a tightlly coupling with EventSoruceInitailizer.

In order to break this tight coupling, it seems that the user can directly inject the EventSource implemented based on the abstract class of EventSource and Cache so that the user can easily access the cache layer as desired even outside the framework.

Below image are my very very rough thoughts. 

![스크린샷 2021-12-03 오후 6 10 53](https://user-images.githubusercontent.com/42938941/144576553-0a76befb-ba07-4c9d-a05b-bb0cabd09965.png)


In the java operator framework, if users can directly implement EventSource through the abstraction layer for EventSource and Cache or selectively inject and use a pre-implemented EventSource, it seems that the cache can be accessed more easily and used flexibly. 🤔

**Comment by metacosm** [comment]
There are some API changes in #760 that offer some improvements on that front that might help with these ideas.

**Comment by csviri** [comment]
Will close this now, we can reopen in case new ideas are popping up

**Comment by metacosm** [comment]
For reference, here's how the dependent resources work on this aspect.

You specify which dependent/secondary resources your primary resource depends on by using annotations on your controller:

```java
@ControllerConfiguration(
    dependents = {
        @Dependent(resourceType = Secret.class, type = SecretDependentResource.class),
        @Dependent(resourceType = Schema.class, type = SchemaDependentResource.class)
    })
public class MySQLSchemaReconciler {}
```

For Kubernetes-native resources, such as `Secret` in the example above, you don't need to deal with event sources at all.  For other resources, such as `Schema` above, your `DependentResource` implementation must provide an initialized `EventSource` instance that the SDK will automatically register when your reconciler registers:

```java
public class SchemaDependentResource implements DependentResource<Schema, MySQLSchema> ... {
...

  @Override
  public EventSource initEventSource(EventSourceContext<MySQLSchema> context) {
    ...
    return new PerResourcePollingEventSource<>(
        new SchemaPollingResourceSupplier(dbConfig), context.getPrimaryCache(), POLL_PERIOD,
        Schema.class);
  }

}
```

For many, "simple" uses cases involving only Kubernetes-native resources, you will never have to deal with `EventSources` at all.
