### ISSUE TITLE
Run integration tests during every build

### ISSUE THREAD

**Issue by adam-sandor** [java-operator-sdk/java-operator-sdk#80]
Either using an always available cluster or spin one up for the tests.

Always on cluster (GKE):
- Constant payments for infrastructure
+ Faster tests
+ Tests upgrades
+ Tests long-running operator

Ad-hoc cluster:
+ Free
- Slow to spin up
- Only tests freshly spun up operator
- Memory leaks and other issues of long-running process don't get tested

**Comment by riccardomc** [comment]
For the externalsecrets-operator I use k3s and helm-test. Check it out: https://github.com/ContainerSolutions/externalsecret-operator/blob/master/.circleci/config.yml#L19

**Comment by adam-sandor** [comment]
Nice, thanks for the tip @riccardomc !

**Comment by psycho-ir** [comment]
I found it indeed crucial to run integration tests for every build. I would be happy to update the [ci.yml](https://github.com/java-operator-sdk/java-operator-sdk/blob/master/.github/workflows/ci.yml) file to run k8s via [kind](https://kind.sigs.k8s.io/) and run integration tests against it. 
What do you folks think?

**Comment by csviri** [comment]
Hi @psycho-ir  
we were thiking to use minikube: https://github.com/marketplace/actions/setup-minikube-kubernetes-cluster
what do you think about using this?

**Comment by psycho-ir** [comment]
I just checked it on my machine with its `docker` driver. 
I take ~150MB more memory comparing with `kind` (833MB vs 677). But on the other hand the docker images of the minikube is significantly smaller (876MB vs 1.33GB). 
Apparently Kind GitHub action is more popular: https://github.com/marketplace/actions/kind-kubernetes-in-docker-action 

I think both should do the job and I personally don't have a strong opinion on either.

**Comment by csviri** [comment]
@psycho-ir I would say use minikube (this kind action is "pre-release") also we use it for local testing.

**Comment by psycho-ir** [comment]
Minikube it is, I'll use it to run the integration tests.
