### ISSUE TITLE
No adapter available for type:class io.fabric8.kubernetes.client.AppsAPIGroupClient

### ISSUE THREAD

**Issue by ZhangChaoming** [java-operator-sdk/java-operator-sdk#823]
## Bug Report

Operator run with expcetion.
```
java.lang.IllegalStateException: No adapter available for type:class io.fabric8.kubernetes.client.AppsAPIGroupClient
        at io.fabric8.kubernetes.client.BaseClient.adapt(BaseClient.java:134) ~[flink-k8s-operator-java-0.0.1-jar-with-dependencies.jar:?]
        at io.fabric8.kubernetes.client.BaseKubernetesClient.apps(BaseKubernetesClient.java:523) ~[flink-k8s-operator-java-0.0.1-jar-with-dependencies.jar:?]
        at cn.qihoo.net.flink.operator.reconciler.DefaultKubernetesJobScheduler.clusterExists(DefaultKubernetesJobScheduler.java:205) ~[flink-k8s-operator-java-0.0.1-jar-with-dependencies.jar:?]

```

#### What did you do?

I use this sdk to build a custom k8s operator.

#### What did you expect to see?

The operator accpets CR them creates a job cluster.

#### What did you see instead? Under which circumstances?

Throw exceprions.

#### Environment

- sdk: operator-framework 2.0.0-M1
- java: 11

#### Possible Solution

I dont't  know.
#### Additional context
```java
Config config = new ConfigBuilder().withNamespace(null).build();
KubernetesClient client = new DefaultKubernetesClient(config);
Operator operator = new Operator(client, DefaultConfigurationService.instance());
operator.register(new XXXReconciler(client));
operator.start();
```

**Comment by csviri** [comment]
Hi @ZhangChaoming could you try ir with RC1, but this seems to be a strange issue. Aren't you override the version of fabric8 kubernetes client used in the project?

**Comment by metacosm** [comment]
A more detailed exception stack would help as well and maybe a way to reproduce the issue?

**Comment by ZhangChaoming** [comment]
I found another version of fabric8 kubernetes client in my dependency. @csviri @metacosm  Thanks .
