### ISSUE TITLE
Remove ability to watch multiple namespaces (its either all or one namespace)

### ISSUE THREAD

**Issue by csviri** [java-operator-sdk/java-operator-sdk#827]
Currently the framework allows to watch either all-namespaces or one namespaces, but also a list of namespaces. The problem is that when we watch a list of namespaces we create a informer for each namespace. This however would anyways complicate things with informers (`InformerEventSource`), so the reconciler would also need to create informers for each namespace. This is problematic, since we can now configure watched namespaces for the controller, **but not supported this for the informers explicitly**. What could also cause confusion.

We should consider/discuss the remove this functionality. So the operator will either watch all or just one namespace. This will mainly simplify the implementation. 

From organisational perspective, usually platform teams deploy operators for the whole cluster. Would it be too hard requirement to deploy the operator for each namespace, if for some reason somebody decides that a production operator needs to handle only selected namespaces.

**Comment by csviri** [comment]
would be good to hear opinions: @metacosm @adam-sandor @andreaTP @lburgazzoli

**Comment by metacosm** [comment]
It would definitely simplify things so I'm in favor of it and I indeed haven't run into use cases where this was needed. Maybe @shawkins or @ppatierno might, though?

**Comment by lburgazzoli** [comment]
+1 to watch either a single namespace or all

**Comment by andreaTP** [comment]
it's fine to watch a single namespace or all.

But, thinking about OLM and future development, we should have an additional layer of filtering (e.g. by `label`s)

**Comment by shawkins** [comment]
I gather since it's accounted for in OLM that some users have pushed for it, but we have not needed to use that feature.

**Comment by lburgazzoli** [comment]
> But, thinking about OLM and future development, we should have an additional layer of filtering (e.g. by `label`s)

AFAIK, in 1.x there were a way to add a label selection when configuring a controller.

**Comment by csviri** [comment]
> it's fine to watch a single namespace or all.
> 
> But, thinking about OLM and future development, we should have an additional layer of filtering (e.g. by `label`s)

filtering by labels is already there.

**Comment by csviri** [comment]
I think this issue is also about the permission, currently it is also possible to filter even by namespace *. 
So if we want to 100% sure that the operator does not have access to other namespaces (thus cluster wide permissions) this might be a useful feature.

* not using the capabilities of Kubernetes API but a custom filter, that receives all the events but filters out the ones which are not for a desired namespace. This is not that nice since there can be lot's of events received unnecessarily.

**Comment by metacosm** [comment]
Indeed, we need to take into account the permission aspects where for many organization giving cluster-wide permissions to an operator is a no-go…

**Comment by csviri** [comment]
Posted this on Operators channel on Kubernetes Slack: https://kubernetes.slack.com/archives/CAW0GV7A5/p1642511565114100

**Comment by metacosm** [comment]
The dependent resource branch deals with this (it has added some generalization around generating informers for each namespace)… As much as I would like to remove this feature since it simplifies things, I think we need to keep it because it helps users who don't want to or cannot deploy their operator with cluster-wide access…

**Comment by csviri** [comment]
As mentioned in the slack in that case it's deployed in every namespace (what is not great, not terrible). But I agree to leave this, if it don't complicate things too much.

**Comment by metacosm** [comment]
> As mentioned in the slack in that case it's deployed in every namespace (what is not great, not terrible). 
How is that done, though, if you have dynamically created namespaces in a multi-tenant environment? Or do you need an operator to automatically deploy your other operator to your namespaces? :)

**Comment by csviri** [comment]
Not sure what you mean by dynamically. In my experience, usually a product team does not have the rights to create namespaces. But the platform team creates for them upfront. In that case event the team could deploy the operator to their namespace(s), if they have the permissions.

**Comment by metacosm** [comment]
> Not sure what you mean by dynamically. 

Consider the OpenShift sandbox use case for example: you sign up, the platform generates a couple of namespaces for you automatically, there's no manual process involved here.

**Comment by scrocquesel** [comment]
Hope I'm not too late.

In our organization, the cluster is multi-tenant and each tenant has only access to a few namespaces. The one given to the tenant and the ones the tenant is able to create on its own.
We can't deploy cluster wide operator.

Currently, we do not use Informer and like @ppatierno we do periodic reconciliations and fetch dependent resource each time.
While it should be possible for some scenario to deploy one controler per namespace, we have some use cases where it will not be possible :

- the reconciler watches CR in many namespaces and dependent resources are in those namespaces, but not necessarly the same as the CR. (Think of an operator syncing resources between namespace). We should be able to create an informer for each target namespaces.
- the reconciler watches CR in one namespaces and should watch for dependent resources in namespaces target by the CR spec. In this case, dependent namespaces to watch are known dynamically from the CR. We should be able to register/unregister informer based on the content of primary cache.

Last case can be mitigated by configuring the operator to watch each namespace a dependent resource is expected to be. The operators must have right on the namespace, so there is already some configuration involved. It would just be an optimization to not create informer on non used namespace.

What I would want to do is something like 

```java
var namespaces = context.getConfigurationService().getConfigurationFor(this).getEffectiveNamespaces();
        return namespaces.stream()
                .map(namespace -> new InformerEventSource<>(
                        client.resources(FooDependent.class).inNamespace(namespace).runnableInformer(0),
                        t -> ...,
                        x -> ...,
                        true))
                .collect(Collectors.toList());
```

**Comment by metacosm** [comment]
> 
>     * the reconciler watches CR in many namespaces and dependent resources are in those namespaces, but not necessarly the same as the CR. (Think of an operator syncing resources between namespace). We should be able to create an informer for each target namespaces.

This use case should be covered by the dependent resources work. If you look at the tomcat sample, you'll see that the `TomcatReconciler` defines dependent resources, one for a `Deployment` and another for a `Service`:
https://github.com/java-operator-sdk/java-operator-sdk/blob/06893df73395a5a2c9d5803c24663159960c53a3/sample-operators/tomcat-operator/src/main/java/io/javaoperatorsdk/operator/sample/TomcatReconciler.java#L26-L32

Since these dependent resources are Kubernetes-one, the SDK automatically generates an `InformerEventSource` for them that you can further configure using the `KubernetesDependent` annotation as seen here:

https://github.com/java-operator-sdk/java-operator-sdk/blob/06893df73395a5a2c9d5803c24663159960c53a3/sample-operators/tomcat-operator/src/main/java/io/javaoperatorsdk/operator/sample/DeploymentDependentResource.java#L12-L15

In the above situation, we're configuring the informer to filter events based on the specified label selector (so that our event source only triggers our `TomcatReconciler` for events targeting `Deployments` with the given label) but you can also specify a list of namespaces using the `namespaces` field on the `KubernetesDependent` annotation, which is what you would use to address your use case. You would specify the list of namespaces for which the SDK needs to listen for dependent events.

>     * the reconciler watches CR in one namespaces and should watch for dependent resources in namespaces target by the CR spec. In this case, dependent namespaces to watch are known dynamically from the CR. We should be able to register/unregister informer based on the content of primary cache.

That's an interesting use case that is not currently covered by the dependent resources work. Would you mind opening an issue to describe the use case in greater detail?

> Last case can be mitigated by configuring the operator to watch each namespace a dependent resource is expected to be. The operators must have right on the namespace, so there is already some configuration involved. It would just be an optimization to not create informer on non used namespace.
> 
> What I would want to do is something like
> 
> ```java
> var namespaces = context.getConfigurationService().getConfigurationFor(this).getEffectiveNamespaces();
>         return namespaces.stream()
>                 .map(namespace -> new InformerEventSource<>(
>                         client.resources(FooDependent.class).inNamespace(namespace).runnableInformer(0),
>                         t -> ...,
>                         x -> ...,
>                         true))
>                 .collect(Collectors.toList());
> ```

Unless I'm misunderstanding what you're saying, I believe this is covered by the `KubernetesDependent` annotation and its `namespaces` field… I would be interested in hearing your feedback to see if it matches your needs…

**Comment by csviri** [comment]
@metacosm @scrocquesel As we discussed before the dependent resources (what is in incubation phase now has this support). But this should be also "elegantly" supported without the dependent resources.

**Comment by metacosm** [comment]
I would suggest that we wait before extracting this feature because I think this makes sense pretty much only in the context of dependent resources. So I would suggest people try it out and let us know how it works for their use cases before investing efforts in extracting that feature and backporting it to the older 2.0.x branch.

**Comment by csviri** [comment]
> I would suggest that we wait before extracting this feature because I think this makes sense pretty much only in the context of dependent resources. So I would suggest people try it out and let us know how it works for their use cases before investing efforts in extracting that feature and backporting it to the older 2.0.x branch.

Why wouldn't it make sense without dependent resources? The lower level API's are meant to be more generic then dependent resources.

**Comment by scrocquesel** [comment]
> > ```
> > * the reconciler watches CR in many namespaces and dependent resources are in those namespaces, but not necessarly the same as the CR. (Think of an operator syncing resources between namespace). We should be able to create an informer for each target namespaces.
> > ```
> 
> This use case should be covered by the dependent resources work. If you look at the tomcat sample, you'll see that the `TomcatReconciler` defines dependent resources, one for a `Deployment` and another for a `Service`:
> 
> https://github.com/java-operator-sdk/java-operator-sdk/blob/06893df73395a5a2c9d5803c24663159960c53a3/sample-operators/tomcat-operator/src/main/java/io/javaoperatorsdk/operator/sample/TomcatReconciler.java#L26-L32
> 
> Since these dependent resources are Kubernetes-one, the SDK automatically generates an `InformerEventSource` for them that you can further configure using the `KubernetesDependent` annotation as seen here:
> 
> https://github.com/java-operator-sdk/java-operator-sdk/blob/06893df73395a5a2c9d5803c24663159960c53a3/sample-operators/tomcat-operator/src/main/java/io/javaoperatorsdk/operator/sample/DeploymentDependentResource.java#L12-L15
> 
> In the above situation, we're configuring the informer to filter events based on the specified label selector (so that our event source only triggers our `TomcatReconciler` for events targeting `Deployments` with the given label) but you can also specify a list of namespaces using the `namespaces` field on the `KubernetesDependent` annotation, which is what you would use to address your use case. You would specify the list of namespaces for which the SDK needs to listen for dependent events.
> 


Yes, looking at the code, it does. Is there an easy way to tell to watch the same namespace as the primary controler ? I think that in the vast majority of use case, dependent resources will be in the same namespaces as the primary resource. So, by default, I would link both configuration. In Quarkus, there is an application.properties to configure namespace of the a controler, and this will avoid to configure the same value twice.


> > ```
> > * the reconciler watches CR in one namespaces and should watch for dependent resources in namespaces target by the CR spec. In this case, dependent namespaces to watch are known dynamically from the CR. We should be able to register/unregister informer based on the content of primary cache.
> > ```
> That's an interesting use case that is not currently covered by the dependent resources work. Would you mind opening an issue to describe the use case in greater detail?
> 

I'll do.

> > Last case can be mitigated by configuring the operator to watch each namespace a dependent resource is expected to be. The operators must have right on the namespace, so there is already some configuration involved. It would just be an optimization to not create informer on non used namespace.
> > What I would want to do is something like
> > ```java
> > var namespaces = context.getConfigurationService().getConfigurationFor(this).getEffectiveNamespaces();
> >         return namespaces.stream()
> >                 .map(namespace -> new InformerEventSource<>(
> >                         client.resources(FooDependent.class).inNamespace(namespace).runnableInformer(0),
> >                         t -> ...,
> >                         x -> ...,
> >                         true))
> >                 .collect(Collectors.toList());
> > ```
> 
> Unless I'm misunderstanding what you're saying, I believe this is covered by the `KubernetesDependent` annotation and its `namespaces` field… I would be interested in hearing your feedback to see if it matches your needs…

Yes, adding event source for each namespace in the Informer does the trick.

**Comment by metacosm** [comment]
This should be closed because there are users who depend on the ability to watch only some namespaces.
