### ISSUE TITLE
[CI] Do not run tests on documentation / web site changes

### ISSUE THREAD

**Issue by metacosm** [java-operator-sdk/java-operator-sdk#835]

**Comment by mstatv** [comment]
Hello question on this one - is the intent to have the CI never run on docs changes? Or is the intent of this issue to have the CI not run when changes are made to docs on PRs, sonar and e2e testing?

**Comment by csviri** [comment]
Hi @mstatv , the intent is if only the docs are changed in a PR, don't run the jobs which executes tests.  Basically now the docs are managed by github (jekyll support), so probably does not make sense to run any of the workflows in that case.

**Comment by mstatv** [comment]
@csviri thank you for the quick response, I'll grab this one if that's cool? Should have a PR. Up today.

**Comment by csviri** [comment]
yep, thank you @mstatv
