### ISSUE TITLE
Operator crashes at startup with NPE on MicrometerMetrics.reconcileCustomResource

### ISSUE THREAD

**Issue by sclorng** [java-operator-sdk/java-operator-sdk#836]
#### What did you do?

I start the operator.

#### What did you expect to see?

Operator running

#### What did you see instead? Under which circumstances?

2022-01-15 17:48:30,163 ERROR traceId= [io.qua.run.Application] (main) Failed to start application (with profile prod): java.lang.NullPointerException
        at io.javaoperatorsdk.operator.monitoring.micrometer.MicrometerMetrics.reconcileCustomResource(MicrometerMetrics.java:63)
        at io.javaoperatorsdk.operator.processing.event.EventProcessor.submitReconciliationExecution(EventProcessor.java:150)
        at io.javaoperatorsdk.operator.processing.event.EventProcessor.handleMarkedEventForResource(EventProcessor.java:134)
        at io.javaoperatorsdk.operator.processing.event.EventProcessor.handleAlreadyMarkedEvents(EventProcessor.java:364)
        at io.javaoperatorsdk.operator.processing.event.EventProcessor.start(EventProcessor.java:356)
        at io.javaoperatorsdk.operator.processing.event.EventSourceManager.start(EventSourceManager.java:77)
        at io.javaoperatorsdk.operator.processing.Controller.start(Controller.java:197)

#### Environment

**Kubernetes cluster type:**

vanilla

`$ Mention java-operator-sdk version from pom.xml file`

2.0.0

`$ java -version`

native GraalVM 21.3

`$ kubectl version`

```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-13T16:12:48Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-15T16:51:04Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

#### Additional context

I'm upgrading several operators and this is the first one that failed at startup. It has two reconciler based on the same abstract class. Using Quarkus Sdk Operator 3.0.0. I import the quarkus-micrometer extension for my own use. Both controller has no event source.

**Comment by sclorng** [comment]
Looking at the code, seems retryState for the marked event source ResourceID don't exist. Don't know if it's normal at startup. Nevertheless maybe MicrometerMetrics.reconcileCustomResource should not assume retryInfo couldn't be null.

**Comment by scrocquesel** [comment]
`EventProcessorTest.startProcessedMarkedEventReceivedBefore` would produce the NPE if micrometers implementation was used instead of `Metrics.NOOP`

I was proposing this fix in micrometer implementation

```
public void reconcileCustomResource(ResourceID resourceID,
      RetryInfo retryInfoNullable) {
    Optional<RetryInfo> retryInfo = Optional.ofNullable(retryInfoNullable);
    incrementCounter(resourceID, RECONCILIATIONS + "started",
        RECONCILIATIONS + "retries.number", "" + retryInfo.map(x -> x.getAttemptCount()).orElse(0),
        RECONCILIATIONS + "retries.last", "" + retryInfo.map(x -> x.isLastAttempt()).orElse(true));
  }
```

but I think that changing signature for `Optional<RetryInfo>` is worthwhile. Still it would be a breaking change.

On testing, there is no test on the micrometer implementation, so I opt for verifying mock call with null value.
But it seems there is no test for verifying call to metrics methods. EventProcess ctors does not allow to pass a Metrics object. Should I add an overload ctor or mock the entire 

```
eventSourceManager
                .getController()
                .getConfiguration()
                .getConfigurationService()
                .getMetrics()
```

chain call ?
