### ISSUE TITLE
Cross Cutting Event Filtering (Aware of Caches?) Before Execution Reconciliation

### ISSUE THREAD

**Issue by csviri** [java-operator-sdk/java-operator-sdk#888]
Within this issues we should investigate a need and use cases for a cross-cutting event filter. That is able to filter out events from all the event sources registered.
Note that v2 although we have a very simplified event handling, so events are propagated are usually just in simplest form, basically just wrapping the target custom resource `ResourceID`, but this could be easily changed, to put more information to the events (accessible only internally now), and those will be accessible from the filter. 

In addition to that there was a use case, described by @lburgazzoli (pls let us know if I describe it poorly)  , when the reconciliation had to be made ideally only when two resources where in a certain state ( like having an annotation with same value on two resources at the same time, so kinda condition on an actual state of resources). In case the filter would have access to the current cache it would make it quite powerful. Note that in general if such a filter would take long to execute and block the thread, could have not desired consequences. 

Notes:
- Let's think/discuss through this properly, maybe also gather other use cases if this is really needed. Since the state checking feels a little un usual for such construct, but without that with the current simplified eventing does not make that much sense.

**Comment by jmrodri** [comment]
There is no pressing need for this feature at the moment. But this was the first time the question had arisen. We captured it as an issue for now. We can discuss more if we need it sooner than later.

**Comment by csviri** [comment]
Will close this issue, since it is not on the radar for a long time, we can reopen in case it pops up in discussions again.
