### ISSUE TITLE
Fix deprecated sample CRD formats 

### ISSUE THREAD

**Issue by csviri** [java-operator-sdk/java-operator-sdk#90]
- in samples the CRD api is still : apiVersion: apiextensions.k8s.io/v1beta1
  it should be apiVersion: apiextensions.k8s.io/v1
- version format also changed of CRD see: 
https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definitions/#create-a-customresourcedefinition

**Comment by teszes** [comment]
Submitted PR on samples repo, don't have rights to it

**Comment by csviri** [comment]
this is fixed (now we mostly generate the CRD)
