### ISSUE TITLE
Tweet on release!

### ISSUE THREAD

**Issue by csviri** [java-operator-sdk/java-operator-sdk#905]
Automatically tweet on the standard JOSDK account on release:
https://twitter.com/javaoperatorsdk
Github action for that:
https://github.com/marketplace/actions/send-tweet-action

**Comment by RishiKumarRay** [comment]
I would like to work on this, it sounds interesting

**Comment by csviri** [comment]
> I would like to work on this, it sounds interesting, i went through the reference , do we need to first create a tweet app, actually i have worked with GitHub actions before but haven't done anything like this, so i would like to try this with your guidance please.

Sure, glad to hear! feel free to create a PR, maybe try to do it with a separate account, we can then setup the credentials for the official changer in the workflow.

**Comment by RishiKumarRay** [comment]
@csviri  separate account of github , you mean ? I read we have to access keys first ?

**Comment by csviri** [comment]
@RishiKumarRay I meant, maybe to experiment with separate twitter account first, to see how it works in you forked repo. Then we can add this as a step in the release workflow with a PR.

**Comment by RishiKumarRay** [comment]
@csviri yeah sure i will do with my own account and let you know, meanwhile please assign it to me so that someone else should not claim this

**Comment by RishiKumarRay** [comment]
@csviri i tried setting up and running , its working i just used this on push event that we can change it was just for testing . please check [here](https://github.com/RishiKumarRay/java-operator-sdk/runs/5090209996?check_suite_focus=true)

**Comment by csviri** [comment]
@RishiKumarRay look good to me, could you create a PR pls?
Maybe we polish the text a bit but otherwise great!

**Comment by RishiKumarRay** [comment]
@csviri yes ofcourse, i will be happy to make PR but before that you need to setup tweeter credentials in secrets by creating an app only after that it will work

**Comment by csviri** [comment]
@RishiKumarRay sure will not merge until that is setup, but PR can be created, also this will be on release, so we can test it just on next release

**Comment by RishiKumarRay** [comment]
@csviri thanks , i have added PR , after adding all secrets , just for testing you can use push event and later on we can test on release event. Thanks looking forward to it.

**Comment by csviri** [comment]
Great, thx!! Will take a look asap
