### ISSUE TITLE
Extract Cleanup Interface from Reconciler

### ISSUE THREAD

**Issue by csviri** [java-operator-sdk/java-operator-sdk#922]
The nice part would be that, this would server also as a switch for the finalizer. So the if the cleanup interface is implemented the finalizers are used otherwise not. 
However then we should probably extract the name customization to a new annotation too. Like `@Finalizer(name = "my-custom-name")` in order to customize the finalizer name.

Original idea from @scrocquesel .

**Comment by csviri** [comment]
Not sure if we should have a separate finalizer annotation, probably would be good enough to have the `finalizerName` stay on `ControllerConfiguration`.

**Comment by csviri** [comment]
A question is what should happen in case of managed dependent resources. If the `Cleaner` interface not implemented by the `Reconciler`.  Still the cleanup should be called for the managed dependent resources?

cc @metacosm

**Comment by metacosm** [comment]
> 

That's a good question… but I'm not sure what the answer should be :)

**Comment by csviri** [comment]
> > Not sure if we should have a separate finalizer annotation, probably would be good enough to have the `finalizerName` stay on `ControllerConfiguration`.
> 
> Maybe the finalizer name should be part of the `Cleaner` interface, with a default implementation matching what we currently have? This way, everything related would be part of the same interface. I'm not sure that this needs to be part of the annotation anymore since, if you want the behavior, you have to implement the `Cleaner` interface and you might as well provide the finalizer name there if you don't like the default one?

Yeah, not sure either, see there three options:
1. Have a separate annotation to configure cleaner.  Like `@CleanerConfiguration`, what would have an attribute `finalizerName`. Or just simply having an annotation `@Finalizer(name="")`. The downside of this is that this will be a separate annotation to handle. The config service would still manage this property?
2. Have it as now on on `@ControllerConfiguration`. The is very easy to implement (basically it is), just could be confusing that one can configure it when there will be no annotation added. (However this is also true for 1.)
3. Have it as a `default` method on the `Cleaner` interface. This would work, but would be nicer I think with annotations, since we already do it for other features.

So honestly I would just stay with variant 2. - document  it, and change it in following versions based on feedback, especially if it would be confusing.

**Comment by csviri** [comment]
Regarding the managed dependent resources. What I would do that maybe separate there the cleanup method to new interface too. And change the behavior based on that. That means:
If the reconciler does not implement the `Cleaner` interface, but there is a dependent resource which does. We will still add the finalizer and call the cleanup on that dependent resource.
