### ISSUE TITLE
Run failed when using the example of WebPage

### ISSUE THREAD

**Issue by zuston** [java-operator-sdk/java-operator-sdk#931]
I just test the example of WebPage in our internal k8s cluster, and use kubectl with the admin role. Pity, it failed.

The operator of WebPage could be started, but when i apply -f "webpage.yaml", it can't accept event from k8s and then no corresponding pods created. 

So i'm confused whether the test case of WebPage is valid. If OK, i have to recheck my k8s config again.

**Comment by zuston** [comment]
Could you help me ? @csviri. 
I'm not familiar with k8s. Thanks

**Comment by csviri** [comment]
Hi @zuston , could you pls send the logs?

**Comment by zuston** [comment]
What log? I can’t attach into operator docker.

**Comment by csviri** [comment]
I assume you can access kubernetes. So you can get the logs from the pod with `kubectl logs <pod name>`.

**Comment by metacosm** [comment]
Are you able to run the example locally, i.e. not deploying the operator on the cluster, first?

**Comment by zuston** [comment]
I found the reason that the opeator yaml is incorrect.
