### ISSUE TITLE
Support building a Docker image and create Kubernetes manifest for the operator

### ISSUE THREAD

**Issue by adam-sandor** [java-operator-sdk/java-operator-sdk#96]
We should help developers not have to worry about how to dockerize and deploy their operators. There are many ways to implement this, one of which is using Quarkus.

Currently, not even all our examples are taking care of this, and it would be much nicer to do it on the SDK level.

**Comment by csviri** [comment]
Will close this issue since it is not on the radar for a long time, we can reopen in case it pops up in discussions again.
